## Pandas Introduction

Pandas has two types of classes for handling data:
* series
* dataframe/DataFrame

**Series** are a one-dimensional labeled array while **DataFrames** are two-dimensional.

We import the pandas package often to aid us in manipulating datasets via the use of the DataFrame object type. Like tables, dataframes have rows and columns. Rows are typically labeled via an index while columns are given specific string labels. Again, like tables, columns must have the same data type, but different columns can contain different data types.  

**Dataframes are index, ordered, and mutable.** Unlike ndarrays, dataframes are always two-dimensional.  Dataframes also have the advantage of permitting us to access data via string labels instead of integer indexes only. 

Dataframes can be created several ways. You'll see a few examples in the code provided in this notebook.

In [11]:
import numpy as np # so we can reference if we needed it - pandas is actually built on top of numpy
import pandas as pd # we typically import as pd

# Create dataframe with 7 rows, columns. 
# Fill with values from the standard normal distribution 
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
df2
#df2.shape

          A         B         C
0  0.030346  0.362193  0.335973
1  0.800628 -0.784990  0.155946
2 -1.203231  0.818341 -0.180231
3 -0.139664 -0.741397 -0.368488
4  0.715520  0.463803  1.031109
5 -1.105624 -0.755894 -0.217310
6 -0.954836 -0.282148 -0.060446

Let's explore the column and row labels.

In [13]:
print(df2.columns)
print(df2.index)
# note that .values will return an array of values

Index(['A', 'B', 'C'], dtype='object')
RangeIndex(start=0, stop=7, step=1)

What about accessing values?  To access and entire column, we can use the dataframe_name['column name']. Mutliple columns require multiple square brackets.

In [15]:
temp = df2['A']
temp

0    0.030346
1    0.800628
2   -1.203231
3   -0.139664
4    0.715520
5   -1.105624
6   -0.954836
Name: A, dtype: float64

Note that what is returned above is actually a **series**.  We can get the same thing by also stating df2.A.

In [17]:
df2.A

0    0.030346
1    0.800628
2   -1.203231
3   -0.139664
4    0.715520
5   -1.105624
6   -0.954836
Name: A, dtype: float64

If you want a dataframe back, you need to use [[]] notation instead.

In [19]:
df2[['A']]

          A
0  0.030346
1  0.800628
2 -1.203231
3 -0.139664
4  0.715520
5 -1.105624
6 -0.954836

We can also use double square brackets to reference more than one column.

In [25]:
print(df2[['A','B']])

          A         B
0  0.030346  0.362193
1  0.800628 -0.784990
2 -1.203231  0.818341
3 -0.139664 -0.741397
4  0.715520  0.463803
5 -1.105624 -0.755894
6 -0.954836 -0.282148

To acccess rows, we need to use the iloc() dataframe method. If we want to refer to items by column labels instead, we can use the the .loc() dataframe method.

In [27]:
df2.iloc[0] # returns the values of the first row

A    0.030346
B    0.362193
C    0.335973
Name: 0, dtype: float64

In [29]:
df2.iloc[0:2] # returns the values of the first two rows

          A         B         C
0  0.030346  0.362193  0.335973
1  0.800628 -0.784990  0.155946

In [31]:
df2.iloc[0, 2] # returns the value in the first row, 3rd column

0.33597330229484546

We can use the iloc and loc to also update individual values.

In [33]:
df2.iloc[0, 2] = 2 # updates the value in the first row, 3rd column
df2

          A         B         C
0  0.030346  0.362193  2.000000
1  0.800628 -0.784990  0.155946
2 -1.203231  0.818341 -0.180231
3 -0.139664 -0.741397 -0.368488
4  0.715520  0.463803  1.031109
5 -1.105624 -0.755894 -0.217310
6 -0.954836 -0.282148 -0.060446

We can also apply slicing to dataframes. Slicing allows you to select multiple rows and/or multiple columns.

In [35]:
df2.iloc[0:2, 1:3]

          B         C
0  0.362193  2.000000
1 -0.784990  0.155946

In [37]:
# can do the same thing
df2.loc[0:2,['B','C']]  # note the use of "loc" vs "iloc"

          B         C
0  0.362193  2.000000
1 -0.784990  0.155946
2  0.818341 -0.180231

In [39]:
# can do the same thing
df2.loc[:2,['B','C']]

          B         C
0  0.362193  2.000000
1 -0.784990  0.155946
2  0.818341 -0.180231

### Filtering data with comparison operators

We can use traditional relational operators to view only a subset of the data as well, much like we'd do with a query. The catch is that the comparison needs to happen between the square brackets.

Consider the two examples below:

In [41]:
df2['A'] > 0

0     True
1     True
2    False
3    False
4     True
5    False
6    False
Name: A, dtype: bool

In [43]:
# vs
df2[df2['A'] > 0]

          A         B         C
0  0.030346  0.362193  2.000000
1  0.800628 -0.784990  0.155946
4  0.715520  0.463803  1.031109

We can combine our tests using & for and, | for or, and ~ for not.  Note these are NOT the bitwise operators, but instead an element-wise operator for use with pandas.

In [49]:
# note that the parens are need to enforce precedence
df2[(df2['A'] > 0) & (df2['C'] > 0)]

          A         B         C
0  0.030346  0.362193  2.000000
1  0.800628 -0.784990  0.155946
4  0.715520  0.463803  1.031109

### Dataframe Methods

Just like there are several methods to use to manipulate ndarrays, pandas include several methods (https://pandas.pydata.org/docs/reference/frame.html) for manipulating dataframes. Common methods to consider include:

* drop() to remove rows or columns
* drop_duplicates() to remove duplicate data
* dropna() to remove missing values
* insert() to insert column in a dataframe
* replace() to replace values in a dataframe
* sort_values() to sort values in a dataframe

In [59]:
# Create dataframe using a list of lists
df = pd.DataFrame([['Bob', 83, 45],
                   ['Ann', 86, 22],
                   ['Lisa', 100, 31],
                   ['J', 51, 22],
                   ['Max', 19, 26],
                   ['Max', 19, 26]])

# Assign column names
df.columns = ['name', 'credits', 'age']

df

   name  credits  age
0   Bob       83   45
1   Ann       86   22
2  Lisa      100   31
3     J       51   22
4   Max       19   26
5   Max       19   26

Pandas provides for easy ways to drop values from the dataframe.

In [61]:
# remove duplicate records
#df = df.drop_duplicates()
df.drop_duplicates(inplace=True)

df  # does this update the original dataset?

   name  credits  age
0   Bob       83   45
1   Ann       86   22
2  Lisa      100   31
3     J       51   22
4   Max       19   26

In [ ]:
df = df.drop_duplicates()
df

There are also easy ways to insert and modify values.

In [63]:
df.insert(loc=0, column='id', value=[123, 234, 345, 567, 675])
df

    id  name  credits  age
0  123   Bob       83   45
1  234   Ann       86   22
2  345  Lisa      100   31
3  567     J       51   22
4  675   Max       19   26

In [ ]:
# Can pair with crazy list comprehensions
df.insert(loc=0, column='class', value=['U' if credits < 120 else "G" for credits in df['credits']])
df

In [65]:
# Adding an empty values so that we can practice removing it
df.loc[0, 'credits'] = np.nan
df

    id  name  credits  age
0  123   Bob      NaN   45
1  234   Ann     86.0   22
2  345  Lisa    100.0   31
3  567     J     51.0   22
4  675   Max     19.0   26

It is important to pay attention to the variety of options when using a given method.  For example, consider dropna().(https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

In [67]:
df.dropna() # default is to remove entire row where missing value is found

    id  name  credits  age
1  234   Ann     86.0   22
2  345  Lisa    100.0   31
3  567     J     51.0   22
4  675   Max     19.0   26

In [ ]:
df.dropna(axis="columns", inplace=True) #drop column where at least one element is missing

In [ ]:
df.dropna(how="all", inplace=True) # drop rows where all elements are missing

In [ ]:
# define what columns to look in
df.dropna(subset=['id', 'credits'])
df

In [ ]:
# Add a column called "credits_remaining" that shows 120 minus credits

df

In [ ]:
# drop that new column
df.drop(columns=["credits_remaining"])
dd

In [ ]:
# dropping rows with index labels (drops 2 rows!!!)
df.drop([0,1]) # drop rows by index

# does this drop in place?
df

In [69]:
# adding a new row
new_row = {"id": 454, "name": "Tony", "age":38}
df.loc[len(df)] = new_row
df

    id  name  credits  age
0  123   Bob      NaN   45
1  234   Ann     86.0   22
2  345  Lisa    100.0   31
3  567     J     51.0   22
4  675   Max     19.0   26
5  454  Tony      NaN   38

We also have a simple way to update values with the replace() method. You can use this with regular expressions as well.

In [ ]:
df.replace(to_replace="J", value="Jay")
df.replace(to_replace="Jay", value="J")

In [ ]:
df['name'] = df['name'].replace(to_replace="J", value="Jay")

Lastly, we can sort the dataframe by a given column.

In [71]:
df.sort_values("name")

    id  name  credits  age
1  234   Ann     86.0   22
0  123   Bob      NaN   45
3  567     J     51.0   22
2  345  Lisa    100.0   31
4  675   Max     19.0   26
5  454  Tony      NaN   38

In [73]:
df.sort_values("name", ascending = False)

    id  name  credits  age
5  454  Tony      NaN   38
4  675   Max     19.0   26
2  345  Lisa    100.0   31
3  567     J     51.0   22
0  123   Bob      NaN   45
1  234   Ann     86.0   22

In [75]:
# soring by multiple columns
df.sort_values(by=['name', 'age'])

    id  name  credits  age
1  234   Ann     86.0   22
0  123   Bob      NaN   45
3  567     J     51.0   22
2  345  Lisa    100.0   31
4  675   Max     19.0   26
5  454  Tony      NaN   38

**Questions**

Consider the dataframe below.

In [ ]:
# dictionary with sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Philadelphia'],
    'Salary': [70000, 80000, 90000, 100000, 75000]
}

# dataFrame created from the dictionary
df = pd.DataFrame(data)

In [ ]:
# get the columns index values
df.columns

In [ ]:
# retrieve just the name column

In [ ]:
# retrieve name and city columns

In [ ]:
# find rows where Age is at least 30

In [ ]:
# Bob's salary is incorrect. Update it to be 95000 instead.

In [ ]:
# View all data in ascending salary order

In [ ]:
# Increase salary for everyone by 10%