## Sources of Data

### Data Repositories

There are many well known data repositories for finding data. A few examples:
* Kaggle - Data Science competition platform. Great for sharing work and finding data sets: https://www.kaggle.com/
* Resources for Business Analytics, Data Mining, and Data Science (including data sets): https://www.kdnuggets.com/
* UC Irvine Machine Learning Repository: https://archive.ics.uci.edu/datasets
* Google: https://datasetsearch.research.google.com/
* Wikipedia: https://en.wikipedia.org/wiki/Wikipedia:Database_download
* Organizations and industries 
    * Nasa: https://www.earthdata.nasa.gov/
    * AWS: https://registry.opendata.aws/
    * IBM: https://developer.imdb.com/non-commercial-datasets/
* Government: https://data.gov/
* Some news sites publish their data sets https://data.fivethirtyeight.com/
* Github

And many more... Many are free... some are not.

While you retrieve data from a data source, to get realtime data you need access to APIs. Webscraping can also be used to obtain realtime access to data but it comes with many challenges (will discuss). 

## Formats

Be aware that data can be in a variety of formats.  Part of your job is to reformat the data for your data science project.
Common formats include:

* flat file (plain or delimited like .csv)
* HTML
* XML
* JSON
* Database

Questions to consider when using a data source

* Is this copyrighted data? 
* Do I need a license to use this data?
* Is it ethical to use this data?
* Is this enough data?
* Can I combine this data with other data?
* Can I scape this data from somewhere? Legally?
* Is an API available for this data?

## APIs

While we can get data using databases and data sets available on sites like Kaggle, we can also get live data from sites. We discussed scraping as one method. The other more reliable method is API use.  

API stands for Application Programming Interface. APIs are used to more easily enable software to communicate. 

Benefits of APIs:
* data is provided in real-time
* can access a lot of data
* data comes to you in a pre-processed format

Common challenges:
* many social media sites now charge a premium to use APIs
* rate limits; you can still be blocked if you abuse the service and don't consider etiquette

### RESTful APIs

APIs exist in different types. One of the popular types, which we will use here is the Representational State Transfer (REST) API. In  RESTful API call, certain constraints are to be followed to adhere to the RESTful style/constraints. 

Calls to APIs depend on 2 things: the endpoint and the operation. The endpoint is the URL for the resource you are accessing. The operation is what operation you want to perform. Common operations are HTTP methods including GET, POST, PUT, and DELETE. Some follow this basic design:

* create operations -> use POST
* read operations -> use GET
* update operations -> use PUT
* delete operations -> used DELETE

For this exercise, you should be familiar with GET requests. The GET request is used to access resources. The POST request is used to send data to a server. For example, we can use the GET request to view data for a given YouTube video posted. We can use a POST request to create a new YouTube video posting. 

Best practices: 
* read the documentation
* cache your requests to avoid unneccessary requests

Many sites have APIs that allow you to access their data more easily. In the past, there was often free tier access with limitations. However, over the recent year we have seen a trend where social media companies are now monetizing more actively their APIs and we are seeing increasing limitations on free API use. So we are going to use a public/open and free API instead.

Note concerning authentication: APIs can also often require an API key or OAuth token that accompanies your request. To make this easier to follow along and start simple, we are going to use some public APIs that don't require authentication.

## Using an APIs in Python

Before working with APIs in code, I prefer to test them using an API tool, like [Postman](https://www.postman.com/). Many API sites in addition to providing documentation also provide resources that help you build API requests. You'll also need to explore the API's documentation in order to determine how to properly make your request. 

See [https://www.mediawiki.org/wiki/API:Tutorial#A_simple_query](https://www.mediawiki.org/wiki/API:Tutorial#A_simple_query) for how to build a simple request. 

We'll use the Python requests library to make API requests. Consider our basic methods from above. We'll use the get() function of this library to perform a basic GET request. This returns a response object.  We can learn a variety of things about a response by looking at the documentation: [https://requests.readthedocs.io/en/latest/](https://requests.readthedocs.io/en/latest/)

If you are using an API key, make sure you store the key securely. That is, don't place it directly into your code. And <strong>never push them out to GitHub</strong>.  See short examples like: [https://worldbank.github.io/template/notebooks/nasa-apod.html](https://worldbank.github.io/template/notebooks/nasa-apod.html) and [https://www.thedataschool.co.uk/daniel-bostrom/how-to-store-environment-variables-in-python-without-them-being-visible-on-github-2/](https://www.thedataschool.co.uk/daniel-bostrom/how-to-store-environment-variables-in-python-without-them-being-visible-on-github-2/) for help, or use a secrets manager.

In [48]:
# required import
import requests
import pandas as pd # we'll need this later

In [1]:


myheaders= {"User-Agent":"MyPythonScript/1.0"} # we will need this... but I want you to see what happens when you forget it

response = requests.get("https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Spock&format=json", headers=myheaders)

In [11]:
# check status code
response.status_code

200

In [13]:
# We can use content attribute to see the body as bytes
response.content

b'{"batchcomplete":"","continue":{"sroffset":10,"continue":"-||"},"query":{"searchinfo":{"totalhits":2014,"suggestion":"slick","suggestionsnippet":"slick"},"search":[{"ns":0,"title":"Spock","pageid":53571,"size":82200,"wordcount":8811,"snippet":"<span class=\\"searchmatch\\">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original","timestamp":"2026-09-09T17:13:57Z"},{"ns":0,"title":"Benjamin Spock","pageid":54522,"size":41746,"wordcount":4520,"snippet":"Benjamin McLane <span class=\\"searchmatch\\">Spock</span> (May 2, 1903 \\u2013 March 15, 1998), widely known as Dr. <span class=\\"searchmatch\\">Spock</span>, was an American pediatrician, Olympic medallist, and left-wing political","timestamp":"2026-08-29T17:36:22Z"},{"ns":0,"title":"Spock (disambiguation)","pageid":18933533,"size":1050,"wordcount":166,"snippet":"Look up <span class=\\"searchmatch\\">Spock</span> in Wiktionary, the free dictionary. <span class=\\"searchmatch\\">Spock</span> is a fictional character in the Star Trek franchise. <span class=\\"searchmatch\\">Spock</span> may also refer to: <span class=\\"searchmatch\\">Spock</span> (surname)","timestamp":"2026-02-01T00:38:52Z"},{"ns":0,"title":"Star Trek III: The Search for Spock","pageid":206879,"size":97370,"wordcount":11865,"snippet":"Star Trek III: The Search for <span class=\\"searchmatch\\">Spock</span> is a 1984 American science fiction film, written and produced by Harve Bennett, directed by Leonard Nimoy, and based","timestamp":"2026-09-15T04:13:07Z"},{"ns":0,"title":"Leonard Nimoy","pageid":53569,"size":100544,"wordcount":9822,"snippet":"and director, famous for playing <span class=\\"searchmatch\\">Spock</span> in the Star Trek franchise for over 40 years. This includes originating <span class=\\"searchmatch\\">Spock</span> in the original Star Trek series","timestamp":"2026-09-06T00:02:30Z"},{"ns":0,"title":"I Am Not Spock","pageid":5302973,"size":7281,"wordcount":677,"snippet":"I Am Not <span class=\\"searchmatch\\">Spock</span> is Leonard Nimoy&#039;s first autobiography. Published in 1975, between the end of Star Trek: The Animated Series and the production of Star","timestamp":"2026-07-02T19:02:19Z"},{"ns":0,"title":"Sarek","pageid":145408,"size":17023,"wordcount":2031,"snippet":"the Vulcan ambassador to the United Federation of Planets, and father of <span class=\\"searchmatch\\">Spock</span>. The character was originally played by Mark Lenard in the episode &quot;Journey","timestamp":"2026-07-15T13:38:44Z"},{"ns":0,"title":"Spock\'s Brain","pageid":413385,"size":16433,"wordcount":1748,"snippet":"&quot;<span class=\\"searchmatch\\">Spock&#039;s</span> Brain&quot; is the third season premiere episode of the American science fiction television series Star Trek. Written by Gene L. Coon (under the pseudonym","timestamp":"2026-07-14T15:57:21Z"},{"ns":0,"title":"Kirk/Spock","pageid":1779398,"size":33952,"wordcount":4067,"snippet":"Kirk/<span class=\\"searchmatch\\">Spock</span>, commonly abbreviated as K/S, or more recently called Spirk and referring to the characters James T. Kirk and <span class=\\"searchmatch\\">Spock</span> from Star Trek, is a popular","timestamp":"2026-09-14T18:08:23Z"},{"ns":0,"title":"Sp\\u00f6ck","pageid":47549377,"size":393,"wordcount":85,"snippet":"<span class=\\"searchmatch\\">Sp\\u00f6ck</span> may refer to: <span class=\\"searchmatch\\">Sp\\u00f6ck</span> (Eider), a river of Schleswig-Holstein, Germany <span class=\\"searchmatch\\">Sp\\u00f6ck</span>, a village in Baden-W\\u00fcrttemberg, Germany, now part of the town of Stutensee","timestamp":"2015-08-17T13:30:18Z"}]}}'

It looks like JSON above... let's use the json() decoder of the response object to access the content.

In [17]:
# get as JSON and store
results = response.json()
# view just the "query" key values
type(results)
results

{'batchcomplete': '',
 'continue': {'sroffset': 10, 'continue': '-||'},
 'query': {'searchinfo': {'totalhits': 2014,
   'suggestion': 'slick',
   'suggestionsnippet': 'slick'},
  'search': [{'ns': 0,
    'title': 'Spock',
    'pageid': 53571,
    'size': 82200,
    'wordcount': 8811,
    'snippet': '<span class="searchmatch">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original',
    'timestamp': '2026-09-09T17:13:57Z'},
   {'ns': 0,
    'title': 'Benjamin Spock',
    'pageid': 54522,
    'size': 41746,
    'wordcount': 4520,
    'snippet': 'Benjamin McLane <span class="searchmatch">Spock</span> (May 2, 1903 – March 15, 1998), widely known as Dr. <span class="searchmatch">Spock</span>, was an American pediatrician, Olympic medallist, and left-wing political',
    'timestamp': '2026-08-29T17:36:22Z'},
   {'ns': 0,
    'title': 'Spock (disambiguation)',
    'pageid': 18933533,
    'size': 1050,
    'wordcount': 166,
    'snippet': 'Look up <span class="searchmatch">Spock</span> in Wiktionary, the free dictionary. <span class="searchmatch">Spock</span> is a fictional character in the Star Trek franchise. <span class="searchmatch">Spock</span> may also refer to: <span class="searchmatch">Spock</span> (surname)',
    'timestamp': '2026-02-01T00:38:52Z'},
   {'ns': 0,
    'title': 'Star Trek III: The Search for Spock',
    'pageid': 206879,
    'size': 97370,
    'wordcount': 11865,
    'snippet': 'Star Trek III: The Search for <span class="searchmatch">Spock</span> is a 1984 American science fiction film, written and produced by Harve Bennett, directed by Leonard Nimoy, and based',
    'timestamp': '2026-09-15T04:13:07Z'},
   {'ns': 0,
    'title': 'Leonard Nimoy',
    'pageid': 53569,
    'size': 100544,
    'wordcount': 9822,
    'snippet': 'and director, famous for playing <span class="searchmatch">Spock</span> in the Star Trek franchise for over 40 years. This includes originating <span class="searchmatch">Spock</span> in the original Star Trek series',
    'timestamp': '2026-09-06T00:02:30Z'},
   {'ns': 0,
    'title': 'I Am Not Spock',
    'pageid': 5302973,
    'size': 7281,
    'wordcount': 677,
    'snippet': 'I Am Not <span class="searchmatch">Spock</span> is Leonard Nimoy&#039;s first autobiography. Published in 1975, between the end of Star Trek: The Animated Series and the production of Star',
    'timestamp': '2026-07-02T19:02:19Z'},
   {'ns': 0,
    'title': 'Sarek',
    'pageid': 145408,
    'size': 17023,
    'wordcount': 2031,
    'snippet': 'the Vulcan ambassador to the United Federation of Planets, and father of <span class="searchmatch">Spock</span>. The character was originally played by Mark Lenard in the episode &quot;Journey',
    'timestamp': '2026-07-15T13:38:44Z'},
   {'ns': 0,
    'title': "Spock's Brain",
    'pageid': 413385,
    'size': 16433,
    'wordcount': 1748,
    'snippet': '&quot;<span class="searchmatch">Spock&#039;s</span> Brain&quot; is the third season premiere episode of the American science fiction television series Star Trek. Written by Gene L. Coon (under the pseudonym',
    'timestamp': '2026-07-14T15:57:21Z'},
   {'ns': 0,
    'title': 'Kirk/Spock',
    'pageid': 1779398,
    'size': 33952,
    'wordcount': 4067,
    'snippet': 'Kirk/<span class="searchmatch">Spock</span>, commonly abbreviated as K/S, or more recently called Spirk and referring to the characters James T. Kirk and <span class="searchmatch">Spock</span> from Star Trek, is a popular',
    'timestamp': '2026-09-14T18:08:23Z'},
   {'ns': 0,
    'title': 'Spöck',
    'pageid': 47549377,
    'size': 393,
    'wordcount': 85,
    'snippet': '<span class="searchmatch">Spöck</span> may refer to: <span class="searchmatch">Spöck</span> (Eider), a river of Schleswig-Holstein, Germany <span class="searchmatch">Spöck</span>, a village in Baden-Württemberg, Germany, now part of the town of Stutensee',
    'timestamp': '2015-08-17T13:30:18Z'}]}}

In [21]:
# all basic search information
# see query searchinfo
results["query"]["searchinfo"]

{'totalhits': 2014, 'suggestion': 'slick', 'suggestionsnippet': 'slick'}

In [23]:
# number of total hits/results
# just get totalhits
results["query"]["searchinfo"]["totalhits"]

2014

In [25]:
# all search results with "spock"
# access search results of query
results["query"]["search"]

[{'ns': 0,
  'title': 'Spock',
  'pageid': 53571,
  'size': 82200,
  'wordcount': 8811,
  'snippet': '<span class="searchmatch">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original',
  'timestamp': '2026-09-09T17:13:57Z'},
 {'ns': 0,
  'title': 'Benjamin Spock',
  'pageid': 54522,
  'size': 41746,
  'wordcount': 4520,
  'snippet': 'Benjamin McLane <span class="searchmatch">Spock</span> (May 2, 1903 – March 15, 1998), widely known as Dr. <span class="searchmatch">Spock</span>, was an American pediatrician, Olympic medallist, and left-wing political',
  'timestamp': '2026-08-29T17:36:22Z'},
 {'ns': 0,
  'title': 'Spock (disambiguation)',
  'pageid': 18933533,
  'size': 1050,
  'wordcount': 166,
  'snippet': 'Look up <span class="searchmatch">Spock</span> in Wiktionary, the free dictionary. <span class="searchmatch">Spock</span> is a fictional character in the Star Trek franchise. <span class="searchmatch">Spock</span> may also refer to: <span class="searchmatch">Spock</span> (surname)',
  'timestamp': '2026-02-01T00:38:52Z'},
 {'ns': 0,
  'title': 'Star Trek III: The Search for Spock',
  'pageid': 206879,
  'size': 97370,
  'wordcount': 11865,
  'snippet': 'Star Trek III: The Search for <span class="searchmatch">Spock</span> is a 1984 American science fiction film, written and produced by Harve Bennett, directed by Leonard Nimoy, and based',
  'timestamp': '2026-09-15T04:13:07Z'},
 {'ns': 0,
  'title': 'Leonard Nimoy',
  'pageid': 53569,
  'size': 100544,
  'wordcount': 9822,
  'snippet': 'and director, famous for playing <span class="searchmatch">Spock</span> in the Star Trek franchise for over 40 years. This includes originating <span class="searchmatch">Spock</span> in the original Star Trek series',
  'timestamp': '2026-09-06T00:02:30Z'},
 {'ns': 0,
  'title': 'I Am Not Spock',
  'pageid': 5302973,
  'size': 7281,
  'wordcount': 677,
  'snippet': 'I Am Not <span class="searchmatch">Spock</span> is Leonard Nimoy&#039;s first autobiography. Published in 1975, between the end of Star Trek: The Animated Series and the production of Star',
  'timestamp': '2026-07-02T19:02:19Z'},
 {'ns': 0,
  'title': 'Sarek',
  'pageid': 145408,
  'size': 17023,
  'wordcount': 2031,
  'snippet': 'the Vulcan ambassador to the United Federation of Planets, and father of <span class="searchmatch">Spock</span>. The character was originally played by Mark Lenard in the episode &quot;Journey',
  'timestamp': '2026-07-15T13:38:44Z'},
 {'ns': 0,
  'title': "Spock's Brain",
  'pageid': 413385,
  'size': 16433,
  'wordcount': 1748,
  'snippet': '&quot;<span class="searchmatch">Spock&#039;s</span> Brain&quot; is the third season premiere episode of the American science fiction television series Star Trek. Written by Gene L. Coon (under the pseudonym',
  'timestamp': '2026-07-14T15:57:21Z'},
 {'ns': 0,
  'title': 'Kirk/Spock',
  'pageid': 1779398,
  'size': 33952,
  'wordcount': 4067,
  'snippet': 'Kirk/<span class="searchmatch">Spock</span>, commonly abbreviated as K/S, or more recently called Spirk and referring to the characters James T. Kirk and <span class="searchmatch">Spock</span> from Star Trek, is a popular',
  'timestamp': '2026-09-14T18:08:23Z'},
 {'ns': 0,
  'title': 'Spöck',
  'pageid': 47549377,
  'size': 393,
  'wordcount': 85,
  'snippet': '<span class="searchmatch">Spöck</span> may refer to: <span class="searchmatch">Spöck</span> (Eider), a river of Schleswig-Holstein, Germany <span class="searchmatch">Spöck</span>, a village in Baden-Württemberg, Germany, now part of the town of Stutensee',
  'timestamp': '2015-08-17T13:30:18Z'}]

In [27]:
# title of first query search result - can use index 0
results["query"]["search"][0]

{'ns': 0,
 'title': 'Spock',
 'pageid': 53571,
 'size': 82200,
 'wordcount': 8811,
 'snippet': '<span class="searchmatch">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original',
 'timestamp': '2026-09-09T17:13:57Z'}

We can put this in a DataFrame to make it easier to work with in our notebook. The json_normalize() function can convert our data to a DataFrame. It accepts a dictionary or a list of dictionaries.

In [29]:
# Let's isolate just the search results
df = pd.json_normalize(results["query"]["search"])

In [31]:
df

,ns,title,pageid,size,wordcount,snippet,timestamp
0,0,Spock,53571,82200,8811,"<span class=""searchmatch"">Spock</span> is a fi...",2026-09-09T17:13:57Z
1,0,Benjamin Spock,54522,41746,4520,"Benjamin McLane <span class=""searchmatch"">Spoc...",2026-08-29T17:36:22Z
2,0,Spock (disambiguation),18933533,1050,166,"Look up <span class=""searchmatch"">Spock</span>...",2026-02-01T00:38:52Z
3,0,Star Trek III: The Search for Spock,206879,97370,11865,"Star Trek III: The Search for <span class=""sea...",2026-09-15T04:13:07Z
4,0,Leonard Nimoy,53569,100544,9822,"and director, famous for playing <span class=""...",2026-09-06T00:02:30Z
5,0,I Am Not Spock,5302973,7281,677,"I Am Not <span class=""searchmatch"">Spock</span...",2026-07-02T19:02:19Z
6,0,Sarek,145408,17023,2031,the Vulcan ambassador to the United Federation...,2026-07-15T13:38:44Z
7,0,Spock's Brain,413385,16433,1748,"&quot;<span class=""searchmatch"">Spock&#039;s</...",2026-07-14T15:57:21Z
8,0,Kirk/Spock,1779398,33952,4067,"Kirk/<span class=""searchmatch"">Spock</span>, c...",2026-09-14T18:08:23Z
9,0,Spöck,47549377,393,85,"<span class=""searchmatch"">Spöck</span> may ref...",2015-08-17T13:30:18Z

In [33]:
# String manipulation
# When we look at the snippet, we see lots of span tags. We can use the pandas replace() function we discussed
# a few weeks ago to fix this

df.replace(to_replace="<span class=\"searchmatch\">", value=" ", inplace = True, regex=True)
df.replace(to_replace="</span>", value=" ", inplace = True, regex=True)
df

,ns,title,pageid,size,wordcount,snippet,timestamp
0,0,Spock,53571,82200,8811,Spock is a fictional character in the Star T...,2026-09-09T17:13:57Z
1,0,Benjamin Spock,54522,41746,4520,"Benjamin McLane Spock (May 2, 1903 – March 1...",2026-08-29T17:36:22Z
2,0,Spock (disambiguation),18933533,1050,166,"Look up Spock in Wiktionary, the free dictio...",2026-02-01T00:38:52Z
3,0,Star Trek III: The Search for Spock,206879,97370,11865,Star Trek III: The Search for Spock is a 198...,2026-09-15T04:13:07Z
4,0,Leonard Nimoy,53569,100544,9822,"and director, famous for playing Spock in th...",2026-09-06T00:02:30Z
5,0,I Am Not Spock,5302973,7281,677,I Am Not Spock is Leonard Nimoy&#039;s first...,2026-07-02T19:02:19Z
6,0,Sarek,145408,17023,2031,the Vulcan ambassador to the United Federation...,2026-07-15T13:38:44Z
7,0,Spock's Brain,413385,16433,1748,&quot; Spock&#039;s Brain&quot; is the third ...,2026-07-14T15:57:21Z
8,0,Kirk/Spock,1779398,33952,4067,"Kirk/ Spock , commonly abbreviated as K/S, or ...",2026-09-14T18:08:23Z
9,0,Spöck,47549377,393,85,"Spöck may refer to: Spöck (Eider), a river...",2015-08-17T13:30:18Z

This is great, but how do we get the next 10 results?

In [39]:
response = requests.get("https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Spock&format=json&continue", headers=myheaders)
response.status_code

200

In [41]:
# this will get paging info and we can store it
params = results["continue"]

In [45]:
# now we'll send it as a parameter in the next request
response = requests.get("https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Spock&format=json&continue", params, headers=myheaders)
response.status_code

200

In [ ]:
response.content

**Question**

Use the https://gutendex.com/ APIs to find books written by "Doyle" and answer the questions below.

In [44]:
# 1. Retrieve the count of books found
# Note... this is slow... takes a minute or two
myheaders = {"User-Agent":"MyPythonScript/1.0"} # we will need this... but I want you to see what happens when you forget it

response = requests.get("https://gutendex.com/books/?search=doyle", headers=myheaders)
response.status_code

200

In [46]:
# 2. Convert results to DataFrame (one book per row)
dict_results = response.json()
df = pd.json_normalize(dict_results["results"])
df

,id,title,authors,summaries,editors,translators,subjects,bookshelves,languages,copyright,...,formats.application/rdf+xml,formats.image/jpeg,formats.application/octet-stream,formats.text/plain; charset=utf-8,formats.text/plain; charset=us-ascii,formats.text/html; charset=utf-8,formats.text/html; charset=iso-8859-1,formats.audio/ogg,formats.audio/mp4,formats.audio/mpeg
0,1661,The Adventures of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Adventures of Sherlock Holmes"" by Arthur...",[],[],"[Detective and mystery stories, English, Holme...","[Banned Books from Anne Haight's list, Categor...",[en],False,...,https://www.gutenberg.org/ebooks/1661.rdf,https://www.gutenberg.org/cache/epub/1661/pg16...,https://www.gutenberg.org/cache/epub/1661/pg16...,https://www.gutenberg.org/ebooks/1661.txt.utf-8,https://www.gutenberg.org/files/1661/1661-0.txt,NaN,NaN,NaN,NaN,NaN
1,2852,The Hound of the Baskervilles,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Hound of the Baskervilles"" by Arthur Con...",[],[],"[Blessing and cursing -- Fiction, Dartmoor (En...","[Bestsellers, American, 1895-1923, Category: B...",[en],False,...,https://www.gutenberg.org/ebooks/2852.rdf,https://www.gutenberg.org/cache/epub/2852/pg28...,https://www.gutenberg.org/cache/epub/2852/pg28...,https://www.gutenberg.org/ebooks/2852.txt.utf-8,https://www.gutenberg.org/files/2852/2852-0.txt,NaN,NaN,NaN,NaN,NaN
2,2097,The Sign of the Four,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Sign of the Four"" by Arthur Conan Doyle ...",[],[],"[Detective and mystery stories, Holmes, Sherlo...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/2097.rdf,https://www.gutenberg.org/cache/epub/2097/pg20...,https://www.gutenberg.org/cache/epub/2097/pg20...,https://www.gutenberg.org/ebooks/2097.txt.utf-8,NaN,NaN,NaN,NaN,NaN,NaN
3,108,The Return of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Return of Sherlock Holmes"" by Arthur Con...",[],[],"[Detective and mystery stories, English, Holme...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/108.rdf,https://www.gutenberg.org/cache/epub/108/pg108...,https://www.gutenberg.org/cache/epub/108/pg108...,https://www.gutenberg.org/ebooks/108.txt.utf-8,NaN,NaN,NaN,NaN,NaN,NaN
4,834,The Memoirs of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Memoirs of Sherlock Holmes"" by Arthur Co...",[],[],"[Detective and mystery stories, English, Holme...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/834.rdf,https://www.gutenberg.org/cache/epub/834/pg834...,https://www.gutenberg.org/cache/epub/834/pg834...,https://www.gutenberg.org/ebooks/834.txt.utf-8,https://www.gutenberg.org/files/834/834-0.txt,NaN,NaN,NaN,NaN,NaN
5,244,A Study in Scarlet,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""A Study in Scarlet"" by Arthur Conan Doyle is...",[],[],"[Detective and mystery stories, England -- Fic...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/244.rdf,https://www.gutenberg.org/cache/epub/244/pg244...,https://www.gutenberg.org/files/244/244-0.zip,https://www.gutenberg.org/ebooks/244.txt.utf-8,NaN,NaN,NaN,NaN,NaN,NaN
6,69700,The case-book of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Case-Book of Sherlock Holmes"" by Arthur ...",[],[],"[Detective and mystery stories, English, Holme...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/69700.rdf,https://www.gutenberg.org/cache/epub/69700/pg6...,https://www.gutenberg.org/cache/epub/69700/pg6...,https://www.gutenberg.org/ebooks/69700.txt.utf-8,https://www.gutenberg.org/files/69700/69700-0.txt,NaN,NaN,NaN,NaN,NaN
7,3289,The Valley of Fear,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Valley of Fear"" by Arthur Conan Doyle is...",[],[],"[Detective and mystery stories, Holmes, Sherlo...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/3289.rdf,https://www.gutenberg.org/cache/epub/3289/pg32...,https://www.gutenberg.org/cache/epub/3289/pg32...,https://www.gutenberg.org/ebooks/3289.txt.utf-8,https://www.gutenberg.org/files/3289/3289-0.txt,NaN,NaN,NaN,NaN,NaN
8,2350,His last bow : $b Some later reminiscences of ...,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""His last bow : Some later reminiscences of S...",[],[],"[Detective and mystery stories, English, Holme...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/2350.rdf,https://www.gutenberg.org/cache/epub/2350/pg23...,https://www.gutenberg.org/cache/epub/2350/pg23...,https://www.gutenberg.org/ebooks/2350.txt.utf-8,https://www.gutenberg.org/files/2350/2350-0.txt,NaN,NaN,NaN,NaN,NaN
9,221,The Return of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Return of Sherlock Holmes"" by Arthur Con...",[],[],"[Detective and mystery stories, English, Holme...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/221.rdf,https://www.gutenberg.org/cache/epub/221/pg221...,https://www.gutenberg.org/cache/epub/221/pg221...,https://www.gutenberg.org/ebooks/221.txt.utf-8,https://www.gutenberg.org/files/221/221.txt,https://www.gutenberg.org/files/221/221-h/221-...,NaN,NaN,NaN,NaN
10,3070,The Hound of the Baskervilles,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Hound of the Baskervilles"" by Arthur Con...",[],[],"[Blessing and cursing -- Fiction, Dartmoor (En...","[Bestsellers, American, 1895-1923, Category: B...",[en],False,...,https://www.gutenberg.org/ebooks/3070.rdf,https://www.gutenberg.org/cache/epub/3070/pg30...,https://www.gutenberg.org/files/3070/3070-8.zip,https://www.gutenberg.org/ebooks/3070.txt.utf-8,https://www.gutenberg.org/files/3070/3070-8.txt,NaN,NaN,NaN,NaN,NaN
11,537,Tales of Terror and Mystery,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Tales of Terror and Mystery"" by Arthur Conan...",[],[],"[Detective and mystery stories, English, Horro...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/537.rdf,https://www.gutenberg.org/cache/epub/537/pg537...,https://www.gutenberg.org/cache/epub/537/pg537...,https://www.gutenberg.org/ebooks/537.txt.utf-8,https://www.gutenberg.org/files/537/537.txt,NaN,https://www.gutenberg.org/files/537/537-h/537-...,NaN,NaN,NaN
12,48320,Adventures of Sherlock Holmes: Illustrated,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Adventures of Sherlock Holmes"" by Arthur Con...",[],[],"[Detective and mystery stories, English, Holme...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/48320.rdf,https://www.gutenberg.org/cache/epub/48320/pg4...,https://www.gutenberg.org/cache/epub/48320/pg4...,https://www.gutenberg.org/ebooks/48320.txt.utf-8,https://www.gutenberg.org/files/48320/48320-0.txt,NaN,NaN,NaN,NaN,NaN
13,76520,Hänen viimeinen tervehdyksensä : $b Muutamia m...,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Hänen viimeinen tervehdyksensä: Muutamia mui...",[],[],"[Detective and mystery stories, English -- Tra...","[Category: British Literature, Category: Class...",[fi],False,...,https://www.gutenberg.org/ebooks/76520.rdf,https://www.gutenberg.org/cache/epub/76520/pg7...,https://www.gutenberg.org/cache/epub/76520/pg7...,https://www.gutenberg.org/ebooks/76520.txt.utf-8,https://www.gutenberg.org/files/76520/76520-0.txt,NaN,NaN,NaN,NaN,NaN
14,76433,La marque des quatre,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[La marque des quatre by Arthur Conan Doyle is...,[],"[{'name': 'Oilliamson, Jeanne de Polignac, com...","[Detective and mystery stories, Holmes, Sherlo...","[Category: British Literature, Category: Class...",[fr],False,...,https://www.gutenberg.org/ebooks/76433.rdf,https://www.gutenberg.org/cache/epub/76433/pg7...,https://www.gutenberg.org/cache/epub/76433/pg7...,https://www.gutenberg.org/ebooks/76433.txt.utf-8,https://www.gutenberg.org/files/76433/76433-0.txt,NaN,NaN,NaN,NaN,NaN
15,139,The Lost World,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Lost World"" by Arthur Conan Doyle is an ...",[],[],"[Challenger, Professor (Fictitious character) ...","[Category: Adventure, Category: British Litera...",[en],False,...,https://www.gutenberg.org/ebooks/139.rdf,https://www.gutenberg.org/cache/epub/139/pg139...,https://www.gutenberg.org/cache/epub/139/pg139...,https://www.gutenberg.org/ebooks/139.txt.utf-8,https://www.gutenberg.org/files/139/139-0.txt,NaN,NaN,NaN,NaN,NaN
16,58574,Index of the Project Gutenberg Works of Arthur...,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Index of the Project Gutenberg Works of Arth...","[{'name': 'Widger, David', 'birth_year': 1932,...",[],[Indexes],[Category: Encyclopedias/Dictionaries/Reference],[en],False,...,https://www.gutenberg.org/ebooks/58574.rdf,https://www.gutenberg.org/cache/epub/58574/pg5...,https://www.gutenberg.org/files/58574/58574-0.zip,https://www.gutenberg.org/ebooks/58574.txt.utf-8,https://www.gutenberg.org/files/58574/58574-0.txt,NaN,NaN,NaN,NaN,NaN
17,28733,The Adventures of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Detective and mystery stories, English, Holme...",[],[en],False,...,https://www.gutenberg.org/ebooks/28733.rdf,https://www.gutenberg.org/cache/epub/28733/pg2...,NaN,NaN,https://www.gutenberg.org/files/28733/28733_re...,NaN,NaN,https://www.gutenberg.org/files/28733/ogg/2873...,https://www.gutenberg.org/files/28733/m4b/2873...,https://www.gutenberg.org/files/28733/mp3/2873...
18,903,The White Company,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The White Company"" by Arthur Conan Doyle is ...",[],[],"[Archers -- Fiction, British -- France -- Fict...","[Category: Adventure, Category: British Litera...",[en],False,...,https://www.gutenberg.org/ebooks/903.rdf,https://www.gutenberg.org/cache/epub/903/pg903...,https://www.gutenberg.org/cache/epub/903/pg903...,https://www.gutenberg.org/ebooks/903.txt.utf-8,https://www.gutenberg.org/files/903/903.txt,https://www.gutenberg.org/files/903/903-h.zip,NaN,NaN,NaN,NaN
19,9551,The Adventures of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Detective and mystery stories, English, Holme...","[Contemporary Reviews, Detective Fiction]",[en],True,...,https://www.gutenberg.org/ebooks/9551.rdf,https://www.gutenberg.org/cache/epub/9551/pg95...,https://www.gutenberg.org/files/9551/9551-mp3-...,NaN,https://www.gutenberg.org/files/9551/9551-read...,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/9551/mp3-16/95...
20,66991,Memories and Adventures,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Memories and Adventures"" by Sir Arthur Conan...",[],[],[Adventure and adventurers -- Great Britain --...,"[Category: Adventure, Category: Biographies]",[en],False,...,https://www.gutenberg.org/ebooks/66991.rdf,https://www.gutenberg.org/cache/epub/66991/pg6...,https://www.gutenberg.org/cache/epub/66991/pg6...,https://www.gutenberg.org/ebooks/66991.txt.utf-8,https://www.gutenberg.org/files/66991/66991-0.txt,NaN,NaN,NaN,NaN,NaN
21,21520,The Hound of the Baskervilles,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Blessing and cursing -- Fiction, Dartmoor (En...","[Bestsellers, American, 1895-1923]",[en],False,...,https://www.gutenberg.org/ebooks/21520.rdf,https://www.gutenberg.org/cache/epub/21520/pg2...,NaN,NaN,https://www.gutenberg.org/files/21520/21520-re...,NaN,NaN,https://www.gutenberg.org/files/21520/ogg/2152...,https://www.gutenberg.org/files/21520/m4b/2152...,https://www.gutenberg.org/files/21520/mp3/2152...
22,9553,The Return of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Detective and mystery stories, English, Holme...",[Detective Fiction],[en],True,...,https://www.gutenberg.org/ebooks/9553.rdf,https://www.gutenberg.org/cache/epub/9553/pg95...,https://www.gutenberg.org/files/9553/9553-mp3-...,NaN,https://www.gutenberg.org/files/9553/9553-read...,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/9553/mp3-16bit...
23,9555,The Memoirs of Sherlock Holmes,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Detective and mystery stories, English, Holme...",[Detective Fiction],[en],True,...,https://www.gutenberg.org/ebooks/9555.rdf,https://www.gutenberg.org/cache/epub/9555/pg95...,https://www.gutenberg.org/files/9555/9555-mp3-...,NaN,https://www.gutenberg.org/files/9555/9555-read...,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/9555/mp3-16bit...
24,26153,The Last of the Legions and Other Tales of Lon...,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Last of the Legions and Other Tales of L...",[],[],"[Adventure stories, English, Historical fictio...","[Category: British Literature, Category: Histo...",[en],False,...,https://www.gutenberg.org/ebooks/26153.rdf,https://www.gutenberg.org/cache/epub/26153/pg2...,https://www.gutenberg.org/files/26153/26153-pa...,https://www.gutenberg.org/ebooks/26153.txt.utf-8,https://www.gutenberg.org/files/26153/26153-0.txt,NaN,NaN,NaN,NaN,NaN
25,2845,Sir Nigel,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Sir Nigel"" by Arthur Conan Doyle is a histor...",[],[],"[Great Britain -- History -- Edward III, 1327-...","[Category: Adventure, Category: British Litera...",[en],False,...,https://www.gutenberg.org/ebooks/2845.rdf,https://www.gutenberg.org/cache/epub/2845/pg28...,https://www.gutenberg.org/files/2845/2845-0.zip,https://www.gutenberg.org/ebooks/2845.txt.utf-8,https://www.gutenberg.org/files/2845/2845-0.txt,NaN,NaN,NaN,NaN,NaN
26,294,"The Captain of the Polestar, and Other Tales","[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Captain of the 'Polestar' and Other Tale...",[],[],[Great Britain -- Social life and customs -- 1...,"[Category: Adventure, Category: British Litera...",[en],False,...,https://www.gutenberg.org/ebooks/294.rdf,https://www.gutenberg.org/cache/epub/294/pg294...,https://www.gutenberg.org/files/294/294-0.zip,https://www.gutenberg.org/ebooks/294.txt.utf-8,https://www.gutenberg.org/files/294/294-0.txt,NaN,NaN,NaN,NaN,NaN
27,21586,The Sign of the Four,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Detective and mystery stories, Holmes, Sherlo...",[],[en],False,...,https://www.gutenberg.org/ebooks/21586.rdf,https://www.gutenberg.org/cache/epub/21586/pg2...,NaN,NaN,https://www.gutenberg.org/files/21586/21586-re...,NaN,NaN,https://www.gutenberg.org/files/21586/ogg/2158...,https://www.gutenberg.org/files/21586/m4b/2158...,https://www.gutenberg.org/files/21586/mp3/2158...
28,3069,The Great Boer War,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Great Boer War"" by Arthur Conan Doyle is...",[],[],"[South African War, 1899-1902]","[Boer War, Category: History - British, Catego...",[en],False,...,https://www.gutenberg.org/ebooks/3069.rdf,https://www.gutenberg.org/cache/epub/3069/pg30...,https://www.gutenberg.org/files/3069/3069-0.zip,https://www.gutenberg.org/ebooks/3069.txt.utf-8,https://www.gutenberg.org/files/3069/3069-0.txt,NaN,NaN,NaN,NaN,NaN
29,54109,Round the Fire Stories,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""Round the Fire Stories"" by Arthur Conan Doyl...",[],[],"[English fiction, Horror tales, English, Short...","[Category: British Literature, Category: Crime...",[en],False,...,https://www.gutenberg.org/ebooks/54109.rdf,https://www.gutenberg.org/cache/epub/54109/pg5...,https://www.gutenberg.org/cache/epub/54109/pg5...,https://www.gutenberg.org/ebooks/54109.txt.utf-8,https://www.gutenberg.org/files/54109/54109-0.txt,NaN,NaN,NaN,NaN,NaN
30,126,The Poison Belt,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...","[""The Poison Belt"" by Arthur Conan Doyle is a ...",[],[],"[Challenger, Professor (Fictitious character) ...","[Category: British Literature, Category: Novel...",[en],False,...,https://www.gutenberg.org/ebooks/126.rdf,https://www.gutenberg.org/cache/epub/126/pg126...,https://www.gutenberg.org/cache/epub/126/pg126...,https://www.gutenberg.org/ebooks/126.txt.utf-8,https://www.gutenberg.org/files/126/126-0.txt,NaN,NaN,NaN,NaN,NaN
31,9552,The Hound of the Baskervilles,"[{'name': 'Doyle, Arthur Conan', 'birth_year':...",[],[],[],"[Blessing and cursing -- Fiction, Dartmoor (En...","[Bestsellers, American, 1895-1923, Detective F...",[en],True,...,https://www.gutenberg.org/ebooks/9552.rdf,https://www.gutenberg.org/cache/epub/9552/pg95...,https://www.gutenberg.org/files/9552/9552-mp3-...,NaN,https://www.gutenberg.org/files/9552/9552-read...,NaN,NaN,NaN,NaN,https://www.gutenberg.org/files/9552/mp3-16/95...

In [50]:
# 3. Do new request. Use API to get information for book with id 2852
# Consider how to craft the URL to obtain just a given book... You'll need to look at the reference for this site.
response = requests.get("https://gutendex.com/books/2852", headers=myheaders)
response = requests.get("https://gutendex.com/books?ids=2852", headers=myheaders)
response.status_code

200

In [52]:
# 4. Print the subjects of this book
result_dict = response.json()
result_dict

{'count': 1,
 'next': None,
 'previous': None,
 'results': [{'id': 2852,
   'title': 'The Hound of the Baskervilles',
   'authors': [{'name': 'Doyle, Arthur Conan',
     'birth_year': 1859,
     'death_year': 1930}],
   'summaries': ['"The Hound of the Baskervilles" by Arthur Conan Doyle is a crime novel serialized from 1901 to 1902. Sherlock Holmes and Watson investigate a centuries-old legend of a demonic hound haunting the Baskerville family on the desolate moors of Dartmoor. When Sir Charles Baskerville dies under mysterious circumstances, his heir Sir Henry arrives from Canada to claim his inheritance—only to face strange threats and supernatural dangers. Holmes must determine whether the curse is real or if a cunning murderer lurks behind the legend. (This is an automatically generated summary.)'],
   'editors': [],
   'translators': [],
   'subjects': ['Blessing and cursing -- Fiction',
    'Dartmoor (England) -- Fiction',
    'Detective and mystery stories',
    'Dogs -- Fiction',
    'Holmes, Sherlock (Fictitious character) -- Fiction',
    'Private investigators -- England -- Fiction'],
   'bookshelves': ['Bestsellers, American, 1895-1923',
    'Category: British Literature',
    'Category: Classics of Literature',
    'Category: Crime, Thrillers and Mystery',
    'Category: Novels',
    'Detective Fiction'],
   'languages': ['en'],
   'copyright': False,
   'media_type': 'Text',
   'formats': {'text/html': 'https://www.gutenberg.org/ebooks/2852.html.images',
    'application/epub+zip': 'https://www.gutenberg.org/ebooks/2852.epub3.images',
    'application/x-mobipocket-ebook': 'https://www.gutenberg.org/ebooks/2852.kf8.images',
    'application/rdf+xml': 'https://www.gutenberg.org/ebooks/2852.rdf',
    'image/jpeg': 'https://www.gutenberg.org/cache/epub/2852/pg2852.cover.medium.jpg',
    'application/octet-stream': 'https://www.gutenberg.org/cache/epub/2852/pg2852-h.zip',
    'text/plain; charset=utf-8': 'https://www.gutenberg.org/ebooks/2852.txt.utf-8',
    'text/plain; charset=us-ascii': 'https://www.gutenberg.org/files/2852/2852-0.txt'},
   'download_count': 75965}]}

In [54]:
result_dict["results"][0]["subjects"]

['Blessing and cursing -- Fiction',
 'Dartmoor (England) -- Fiction',
 'Detective and mystery stories',
 'Dogs -- Fiction',
 'Holmes, Sherlock (Fictitious character) -- Fiction',
 'Private investigators -- England -- Fiction']