## Sources of Data

### Data Repositories

There are many well known data repositories for finding data. A few examples:
* Kaggle - Data Science competition platform. Great for sharing work and finding data sets: https://www.kaggle.com/
* Resources for Business Analytics, Data Mining, and Data Science (including data sets): https://www.kdnuggets.com/
* UC Irvine Machine Learning Repository: https://archive.ics.uci.edu/datasets
* Google: https://datasetsearch.research.google.com/
* Wikipedia: https://en.wikipedia.org/wiki/Wikipedia:Database_download
* Organizations and industries 
    * Nasa: https://www.earthdata.nasa.gov/
    * AWS: https://registry.opendata.aws/
    * IBM: https://developer.imdb.com/non-commercial-datasets/
* Government: https://data.gov/
* Some news sites publish their data sets https://data.fivethirtyeight.com/
* Github

And many more... Many are free... some are not.

While you retrieve data from a data source, to get realtime data you need access to APIs. Webscraping can also be used to obtain realtime access to data but it comes with many challenges (will discuss). 

## Formats

Be aware that data can be in a variety of formats.  Part of your job is to reformat the data for your data science project.
Common formats include:

* flat file (plain or delimited like .csv)
* HTML
* XML
* JSON
* Database

Questions to consider when using a data source

* Is this copyrighted data? 
* Do I need a license to use this data?
* Is it ethical to use this data?
* Is this enough data?
* Can I combine this data with other data?
* Can I scape this data from somewhere? Legally?
* Is an API available for this data?

## APIs

While we can get data using databases and data sets available on sites like Kaggle, we can also get live data from sites. We discussed scraping as one method. The other more reliable method is API use.  

API stands for Application Programming Interface. APIs are used to more easily enable software to communicate. 

Benefits of APIs:
* data is provided in real-time
* can access a lot of data
* data comes to you in a pre-processed format

Common challenges:
* many social media sites now charge a premium to use APIs
* rate limits; you can still be blocked if you abuse the service and don't consider etiquette

### RESTful APIs

APIs exist in different types. One of the popular types, which we will use here is the Representational State Transfer (REST) API. In  RESTful API call, certain constraints are to be followed to adhere to the RESTful style/constraints. 

Calls to APIs depend on 2 things: the endpoint and the operation. The endpoint is the URL for the resource you are accessing. The operation is what operation you want to perform. Common operations are HTTP methods including GET, POST, PUT, and DELETE. Some follow this basic design:

* create operations -> use POST
* read operations -> use GET
* update operations -> use PUT
* delete operations -> used DELETE

For this exercise, you should be familiar with GET requests. The GET request is used to access resources. The POST request is used to send data to a server. For example, we can use the GET request to view data for a given YouTube video posted. We can use a POST request to create a new YouTube video posting. 

Best practices: 
* read the documentation
* cache your requests to avoid unneccessary requests

Many sites have APIs that allow you to access their data more easily. In the past, there was often free tier access with limitations. However, over the recent year we have seen a trend where social media companies are now monetizing more actively their APIs and we are seeing increasing limitations on free API use. So we are going to use a public/open and free API instead.

Note concerning authentication: APIs can also often require an API key or OAuth token that accompanies your request. To make this easier to follow along and start simple, we are going to use some public APIs that don't require authentication.

## Using an APIs in Python

Before working with APIs in code, I prefer to test them using an API tool, like [Postman](https://www.postman.com/). Many API sites in addition to providing documentation also provide resources that help you build API requests. You'll also need to explore the API's documentation in order to determine how to properly make your request. 

See [https://www.mediawiki.org/wiki/API:Tutorial#A_simple_query](https://www.mediawiki.org/wiki/API:Tutorial#A_simple_query) for how to build a simple request. 

We'll use the Python requests library to make API requests. Consider our basic methods from above. We'll use the get() function of this library to perform a basic GET request. This returns a response object.  We can learn a variety of things about a response by looking at the documentation: [https://requests.readthedocs.io/en/latest/](https://requests.readthedocs.io/en/latest/)

If you are using an API key, make sure you store the key securely. That is, don't place it directly into your code. And <strong>never push them out to GitHub</strong>.  See short examples like: [https://worldbank.github.io/template/notebooks/nasa-apod.html](https://worldbank.github.io/template/notebooks/nasa-apod.html) and [https://www.thedataschool.co.uk/daniel-bostrom/how-to-store-environment-variables-in-python-without-them-being-visible-on-github-2/](https://www.thedataschool.co.uk/daniel-bostrom/how-to-store-environment-variables-in-python-without-them-being-visible-on-github-2/) for help, or use a secrets manager.

In [9]:
# required import
import requests
import pandas as pd # we'll need this later

myheaders= {"User-Agent":"MyPythonScript/1.0"} # we will need this... but I want you to see what happens when you forget it

response = requests.get("https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Spock&format=json", headers=myheaders)

In [11]:
# check status code
response.status_code

200

In [13]:
# We can use content attribute to see the body as bytes
response.content

b'{"batchcomplete":"","continue":{"sroffset":10,"continue":"-||"},"query":{"searchinfo":{"totalhits":2014,"suggestion":"slick","suggestionsnippet":"slick"},"search":[{"ns":0,"title":"Spock","pageid":53571,"size":82200,"wordcount":8811,"snippet":"<span class=\\"searchmatch\\">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original","timestamp":"2026-09-09T17:13:57Z"},{"ns":0,"title":"Benjamin Spock","pageid":54522,"size":41746,"wordcount":4520,"snippet":"Benjamin McLane <span class=\\"searchmatch\\">Spock</span> (May 2, 1903 \\u2013 March 15, 1998), widely known as Dr. <span class=\\"searchmatch\\">Spock</span>, was an American pediatrician, Olympic medallist, and left-wing political","timestamp":"2026-08-29T17:36:22Z"},{"ns":0,"title":"Spock (disambiguation)","pageid":18933533,"size":1050,"wordcount":166,"snippet":"Look up <span class=\\"searchmatch\\">Spock</span> in Wiktionary, the free dictionary. <span class=\\"searchmatch\\">Spock</span> is a fictional character in the Star Trek franchise. <span class=\\"searchmatch\\">Spock</span> may also refer to: <span class=\\"searchmatch\\">Spock</span> (surname)","timestamp":"2026-02-01T00:38:52Z"},{"ns":0,"title":"Star Trek III: The Search for Spock","pageid":206879,"size":97370,"wordcount":11865,"snippet":"Star Trek III: The Search for <span class=\\"searchmatch\\">Spock</span> is a 1984 American science fiction film, written and produced by Harve Bennett, directed by Leonard Nimoy, and based","timestamp":"2026-09-15T04:13:07Z"},{"ns":0,"title":"Leonard Nimoy","pageid":53569,"size":100544,"wordcount":9822,"snippet":"and director, famous for playing <span class=\\"searchmatch\\">Spock</span> in the Star Trek franchise for over 40 years. This includes originating <span class=\\"searchmatch\\">Spock</span> in the original Star Trek series","timestamp":"2026-09-06T00:02:30Z"},{"ns":0,"title":"I Am Not Spock","pageid":5302973,"size":7281,"wordcount":677,"snippet":"I Am Not <span class=\\"searchmatch\\">Spock</span> is Leonard Nimoy&#039;s first autobiography. Published in 1975, between the end of Star Trek: The Animated Series and the production of Star","timestamp":"2026-07-02T19:02:19Z"},{"ns":0,"title":"Sarek","pageid":145408,"size":17023,"wordcount":2031,"snippet":"the Vulcan ambassador to the United Federation of Planets, and father of <span class=\\"searchmatch\\">Spock</span>. The character was originally played by Mark Lenard in the episode &quot;Journey","timestamp":"2026-07-15T13:38:44Z"},{"ns":0,"title":"Spock\'s Brain","pageid":413385,"size":16433,"wordcount":1748,"snippet":"&quot;<span class=\\"searchmatch\\">Spock&#039;s</span> Brain&quot; is the third season premiere episode of the American science fiction television series Star Trek. Written by Gene L. Coon (under the pseudonym","timestamp":"2026-07-14T15:57:21Z"},{"ns":0,"title":"Kirk/Spock","pageid":1779398,"size":33952,"wordcount":4067,"snippet":"Kirk/<span class=\\"searchmatch\\">Spock</span>, commonly abbreviated as K/S, or more recently called Spirk and referring to the characters James T. Kirk and <span class=\\"searchmatch\\">Spock</span> from Star Trek, is a popular","timestamp":"2026-09-14T18:08:23Z"},{"ns":0,"title":"Sp\\u00f6ck","pageid":47549377,"size":393,"wordcount":85,"snippet":"<span class=\\"searchmatch\\">Sp\\u00f6ck</span> may refer to: <span class=\\"searchmatch\\">Sp\\u00f6ck</span> (Eider), a river of Schleswig-Holstein, Germany <span class=\\"searchmatch\\">Sp\\u00f6ck</span>, a village in Baden-W\\u00fcrttemberg, Germany, now part of the town of Stutensee","timestamp":"2015-08-17T13:30:18Z"}]}}'

It looks like JSON above... let's use the json() decoder of the response object to access the content.

In [17]:
# get as JSON and store
results = response.json()
# view just the "query" key values
type(results)
results

{'batchcomplete': '',
 'continue': {'sroffset': 10, 'continue': '-||'},
 'query': {'searchinfo': {'totalhits': 2014,
   'suggestion': 'slick',
   'suggestionsnippet': 'slick'},
  'search': [{'ns': 0,
    'title': 'Spock',
    'pageid': 53571,
    'size': 82200,
    'wordcount': 8811,
    'snippet': '<span class="searchmatch">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original',
    'timestamp': '2026-09-09T17:13:57Z'},
   {'ns': 0,
    'title': 'Benjamin Spock',
    'pageid': 54522,
    'size': 41746,
    'wordcount': 4520,
    'snippet': 'Benjamin McLane <span class="searchmatch">Spock</span> (May 2, 1903 – March 15, 1998), widely known as Dr. <span class="searchmatch">Spock</span>, was an American pediatrician, Olympic medallist, and left-wing political',
    'timestamp': '2026-08-29T17:36:22Z'},
   {'ns': 0,
    'title': 'Spock (disambiguation)',
    'pageid': 18933533,
    'size': 1050,
    'wordcount': 166,
    'snippet': 'Look up <span class="searchmatch">Spock</span> in Wiktionary, the free dictionary. <span class="searchmatch">Spock</span> is a fictional character in the Star Trek franchise. <span class="searchmatch">Spock</span> may also refer to: <span class="searchmatch">Spock</span> (surname)',
    'timestamp': '2026-02-01T00:38:52Z'},
   {'ns': 0,
    'title': 'Star Trek III: The Search for Spock',
    'pageid': 206879,
    'size': 97370,
    'wordcount': 11865,
    'snippet': 'Star Trek III: The Search for <span class="searchmatch">Spock</span> is a 1984 American science fiction film, written and produced by Harve Bennett, directed by Leonard Nimoy, and based',
    'timestamp': '2026-09-15T04:13:07Z'},
   {'ns': 0,
    'title': 'Leonard Nimoy',
    'pageid': 53569,
    'size': 100544,
    'wordcount': 9822,
    'snippet': 'and director, famous for playing <span class="searchmatch">Spock</span> in the Star Trek franchise for over 40 years. This includes originating <span class="searchmatch">Spock</span> in the original Star Trek series',
    'timestamp': '2026-09-06T00:02:30Z'},
   {'ns': 0,
    'title': 'I Am Not Spock',
    'pageid': 5302973,
    'size': 7281,
    'wordcount': 677,
    'snippet': 'I Am Not <span class="searchmatch">Spock</span> is Leonard Nimoy&#039;s first autobiography. Published in 1975, between the end of Star Trek: The Animated Series and the production of Star',
    'timestamp': '2026-07-02T19:02:19Z'},
   {'ns': 0,
    'title': 'Sarek',
    'pageid': 145408,
    'size': 17023,
    'wordcount': 2031,
    'snippet': 'the Vulcan ambassador to the United Federation of Planets, and father of <span class="searchmatch">Spock</span>. The character was originally played by Mark Lenard in the episode &quot;Journey',
    'timestamp': '2026-07-15T13:38:44Z'},
   {'ns': 0,
    'title': "Spock's Brain",
    'pageid': 413385,
    'size': 16433,
    'wordcount': 1748,
    'snippet': '&quot;<span class="searchmatch">Spock&#039;s</span> Brain&quot; is the third season premiere episode of the American science fiction television series Star Trek. Written by Gene L. Coon (under the pseudonym',
    'timestamp': '2026-07-14T15:57:21Z'},
   {'ns': 0,
    'title': 'Kirk/Spock',
    'pageid': 1779398,
    'size': 33952,
    'wordcount': 4067,
    'snippet': 'Kirk/<span class="searchmatch">Spock</span>, commonly abbreviated as K/S, or more recently called Spirk and referring to the characters James T. Kirk and <span class="searchmatch">Spock</span> from Star Trek, is a popular',
    'timestamp': '2026-09-14T18:08:23Z'},
   {'ns': 0,
    'title': 'Spöck',
    'pageid': 47549377,
    'size': 393,
    'wordcount': 85,
    'snippet': '<span class="searchmatch">Spöck</span> may refer to: <span class="searchmatch">Spöck</span> (Eider), a river of Schleswig-Holstein, Germany <span class="searchmatch">Spöck</span>, a village in Baden-Württemberg, Germany, now part of the town of Stutensee',
    'timestamp': '2015-08-17T13:30:18Z'}]}}

In [21]:
# all basic search information
# see query searchinfo
results["query"]["searchinfo"]

{'totalhits': 2014, 'suggestion': 'slick', 'suggestionsnippet': 'slick'}

In [23]:
# number of total hits/results
# just get totalhits
results["query"]["searchinfo"]["totalhits"]

2014

In [25]:
# all search results with "spock"
# access search results of query
results["query"]["search"]

[{'ns': 0,
  'title': 'Spock',
  'pageid': 53571,
  'size': 82200,
  'wordcount': 8811,
  'snippet': '<span class="searchmatch">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original',
  'timestamp': '2026-09-09T17:13:57Z'},
 {'ns': 0,
  'title': 'Benjamin Spock',
  'pageid': 54522,
  'size': 41746,
  'wordcount': 4520,
  'snippet': 'Benjamin McLane <span class="searchmatch">Spock</span> (May 2, 1903 – March 15, 1998), widely known as Dr. <span class="searchmatch">Spock</span>, was an American pediatrician, Olympic medallist, and left-wing political',
  'timestamp': '2026-08-29T17:36:22Z'},
 {'ns': 0,
  'title': 'Spock (disambiguation)',
  'pageid': 18933533,
  'size': 1050,
  'wordcount': 166,
  'snippet': 'Look up <span class="searchmatch">Spock</span> in Wiktionary, the free dictionary. <span class="searchmatch">Spock</span> is a fictional character in the Star Trek franchise. <span class="searchmatch">Spock</span> may also refer to: <span class="searchmatch">Spock</span> (surname)',
  'timestamp': '2026-02-01T00:38:52Z'},
 {'ns': 0,
  'title': 'Star Trek III: The Search for Spock',
  'pageid': 206879,
  'size': 97370,
  'wordcount': 11865,
  'snippet': 'Star Trek III: The Search for <span class="searchmatch">Spock</span> is a 1984 American science fiction film, written and produced by Harve Bennett, directed by Leonard Nimoy, and based',
  'timestamp': '2026-09-15T04:13:07Z'},
 {'ns': 0,
  'title': 'Leonard Nimoy',
  'pageid': 53569,
  'size': 100544,
  'wordcount': 9822,
  'snippet': 'and director, famous for playing <span class="searchmatch">Spock</span> in the Star Trek franchise for over 40 years. This includes originating <span class="searchmatch">Spock</span> in the original Star Trek series',
  'timestamp': '2026-09-06T00:02:30Z'},
 {'ns': 0,
  'title': 'I Am Not Spock',
  'pageid': 5302973,
  'size': 7281,
  'wordcount': 677,
  'snippet': 'I Am Not <span class="searchmatch">Spock</span> is Leonard Nimoy&#039;s first autobiography. Published in 1975, between the end of Star Trek: The Animated Series and the production of Star',
  'timestamp': '2026-07-02T19:02:19Z'},
 {'ns': 0,
  'title': 'Sarek',
  'pageid': 145408,
  'size': 17023,
  'wordcount': 2031,
  'snippet': 'the Vulcan ambassador to the United Federation of Planets, and father of <span class="searchmatch">Spock</span>. The character was originally played by Mark Lenard in the episode &quot;Journey',
  'timestamp': '2026-07-15T13:38:44Z'},
 {'ns': 0,
  'title': "Spock's Brain",
  'pageid': 413385,
  'size': 16433,
  'wordcount': 1748,
  'snippet': '&quot;<span class="searchmatch">Spock&#039;s</span> Brain&quot; is the third season premiere episode of the American science fiction television series Star Trek. Written by Gene L. Coon (under the pseudonym',
  'timestamp': '2026-07-14T15:57:21Z'},
 {'ns': 0,
  'title': 'Kirk/Spock',
  'pageid': 1779398,
  'size': 33952,
  'wordcount': 4067,
  'snippet': 'Kirk/<span class="searchmatch">Spock</span>, commonly abbreviated as K/S, or more recently called Spirk and referring to the characters James T. Kirk and <span class="searchmatch">Spock</span> from Star Trek, is a popular',
  'timestamp': '2026-09-14T18:08:23Z'},
 {'ns': 0,
  'title': 'Spöck',
  'pageid': 47549377,
  'size': 393,
  'wordcount': 85,
  'snippet': '<span class="searchmatch">Spöck</span> may refer to: <span class="searchmatch">Spöck</span> (Eider), a river of Schleswig-Holstein, Germany <span class="searchmatch">Spöck</span>, a village in Baden-Württemberg, Germany, now part of the town of Stutensee',
  'timestamp': '2015-08-17T13:30:18Z'}]

In [27]:
# title of first query search result - can use index 0
results["query"]["search"][0]

{'ns': 0,
 'title': 'Spock',
 'pageid': 53571,
 'size': 82200,
 'wordcount': 8811,
 'snippet': '<span class="searchmatch">Spock</span> is a fictional character in the Star Trek media franchise. Portrayed by Leonard Nimoy, he is one of the three central characters in the original',
 'timestamp': '2026-09-09T17:13:57Z'}

We can put this in a DataFrame to make it easier to work with in our notebook. The json_normalize() function can convert our data to a DataFrame. It accepts a dictionary or a list of dictionaries.

In [29]:
# Let's isolate just the search results
df = pd.json_normalize(results["query"]["search"])

In [31]:
df

,ns,title,pageid,size,wordcount,snippet,timestamp
0,0,Spock,53571,82200,8811,"<span class=""searchmatch"">Spock</span> is a fi...",2026-09-09T17:13:57Z
1,0,Benjamin Spock,54522,41746,4520,"Benjamin McLane <span class=""searchmatch"">Spoc...",2026-08-29T17:36:22Z
2,0,Spock (disambiguation),18933533,1050,166,"Look up <span class=""searchmatch"">Spock</span>...",2026-02-01T00:38:52Z
3,0,Star Trek III: The Search for Spock,206879,97370,11865,"Star Trek III: The Search for <span class=""sea...",2026-09-15T04:13:07Z
4,0,Leonard Nimoy,53569,100544,9822,"and director, famous for playing <span class=""...",2026-09-06T00:02:30Z
5,0,I Am Not Spock,5302973,7281,677,"I Am Not <span class=""searchmatch"">Spock</span...",2026-07-02T19:02:19Z
6,0,Sarek,145408,17023,2031,the Vulcan ambassador to the United Federation...,2026-07-15T13:38:44Z
7,0,Spock's Brain,413385,16433,1748,"&quot;<span class=""searchmatch"">Spock&#039;s</...",2026-07-14T15:57:21Z
8,0,Kirk/Spock,1779398,33952,4067,"Kirk/<span class=""searchmatch"">Spock</span>, c...",2026-09-14T18:08:23Z
9,0,Spöck,47549377,393,85,"<span class=""searchmatch"">Spöck</span> may ref...",2015-08-17T13:30:18Z

In [33]:
# String manipulation
# When we look at the snippet, we see lots of span tags. We can use the pandas replace() function we discussed
# a few weeks ago to fix this

df.replace(to_replace="<span class=\"searchmatch\">", value=" ", inplace = True, regex=True)
df.replace(to_replace="</span>", value=" ", inplace = True, regex=True)
df

,ns,title,pageid,size,wordcount,snippet,timestamp
0,0,Spock,53571,82200,8811,Spock is a fictional character in the Star T...,2026-09-09T17:13:57Z
1,0,Benjamin Spock,54522,41746,4520,"Benjamin McLane Spock (May 2, 1903 – March 1...",2026-08-29T17:36:22Z
2,0,Spock (disambiguation),18933533,1050,166,"Look up Spock in Wiktionary, the free dictio...",2026-02-01T00:38:52Z
3,0,Star Trek III: The Search for Spock,206879,97370,11865,Star Trek III: The Search for Spock is a 198...,2026-09-15T04:13:07Z
4,0,Leonard Nimoy,53569,100544,9822,"and director, famous for playing Spock in th...",2026-09-06T00:02:30Z
5,0,I Am Not Spock,5302973,7281,677,I Am Not Spock is Leonard Nimoy&#039;s first...,2026-07-02T19:02:19Z
6,0,Sarek,145408,17023,2031,the Vulcan ambassador to the United Federation...,2026-07-15T13:38:44Z
7,0,Spock's Brain,413385,16433,1748,&quot; Spock&#039;s Brain&quot; is the third ...,2026-07-14T15:57:21Z
8,0,Kirk/Spock,1779398,33952,4067,"Kirk/ Spock , commonly abbreviated as K/S, or ...",2026-09-14T18:08:23Z
9,0,Spöck,47549377,393,85,"Spöck may refer to: Spöck (Eider), a river...",2015-08-17T13:30:18Z

This is great, but how do we get the next 10 results?

In [39]:
response = requests.get("https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Spock&format=json&continue", headers=myheaders)
response.status_code

200

In [41]:
# this will get paging info and we can store it
params = results["continue"]

In [45]:
# now we'll send it as a parameter in the next request
response = requests.get("https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Spock&format=json&continue", params, headers=myheaders)
response.status_code

200

In [ ]:
response.content

**Question**

Use the https://gutendex.com/ APIs to find books written by "Doyle" and answer the questions below.

In [47]:
# 1. Retrieve the count of books found
# Note... this is slow... takes a minute or two
myheaders= {"User-Agent":"MyPythonScript/1.0"} # we will need this... but I want you to see what happens when you forget it

response = requests.get("https://gutendex.com/books/?search=doyle", headers=myheaders)
response.status_code

200

In [ ]:
# 2. Convert results to DataFrame (one book per row)

In [ ]:
# 3. Do new request. Use API to get information for book with id 2852
# Consider how to craft the URL to obtain just a given book... You'll need to look at the reference for this site.

In [ ]:
# 4. Print the subjects of this book