## Data Wrangling

Recall our data wrangling process. The slides and this week's chapter detail the process.  

1. Discovering
2. Structuring
3. Cleaning 
4. Enriching
5. Validating
6. Publishing

We'll explore the process and the various techniques that can be used in Python to address the steps.

IMPORTANT NOTE: USE YOUR NOTEBOOK TO KEEP TRACK OF HOW YOU CLEANED DATA. NEVER CHANGE DATA AND THEN REMOVE THE CODE THAT CHANGED THE DATA.

### 1. Discovering

We have found data concerning college student food preferences. This data is the result of a student survey at Mercyhurst University. The file is: food_coded.csv

Data is from https://www.kaggle.com/datasets/borapajo/food-choices/data. About the data: "This dataset includes information on food choices, nutrition, preferences, childhood favorites, and other information from college students. There are 126 responses from students. Data is raw and uncleaned." Warning: there is some profanity. 

Let's do our import and load this data.

In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
# Load the dataset
df = pd.read_csv("food_coded.csv")

In [70]:
# Do our typical review of the data to get started
# see first five and last five observations
df

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,2.0,9,NaN,eat good and exercise,1,1.0,eat faster,1,1,3,3.0,1,1.0,5.0,profesor,Arabic cuisine,3,1.0,rice and chicken,2,5,2,5,2,looks not oily,being healthy,8,5.0,5,5,1.0,1.0,"rice, chicken, soup",1.0,unemployed,5,1.0,1,2,5.0,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks...,2,2.0,I eat out more than usual.,1,2,2,2.0,4,1.0,2.0,Self employed,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies),...",Try to eat 5-6 small meals a day. While trying...,3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken",4.0,Nurse RN,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,1,3.0,"toast and fruit for breakfast, salad for lunch...",3,1.0,sometimes choosing to eat fast food instead of...,1,3,2,3.0,5,2.0,2.0,owns business,italian,1,3.0,"mac and cheese, pizza, tacos",1,5,3,5,6,usually includes natural ingredients; nonproce...,i would say my ideal diet is my current diet,6,6.0,5,5,7.0,2.0,"chicken and rice with veggies, pasta, some kin...",2.0,owns business,4,2.0,1,3,5.0,6.0,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,2.0,2,2.0,"College diet, cheap and easy foods most nights...",2,2.0,Accepting cheap and premade/store bought foods,1,3,2,3.0,5,3.0,2.0,Mechanic,Turkish,3,1.0,"Beef stroganoff, tacos, pizza",2,4,4,5,7,"Fresh fruits& vegetables, organic meats","Healthy, fresh veggies/fruits & organic foods",2,6.0,5,5,2.0,2.0,Grilled chicken \rStuffed Shells\rHomemade Chili,4.0,Special Education Teacher,2,1.0,1,2,5.0,5.0,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,1.0,1,2.0,I try to eat healthy but often struggle becaus...,2,2.0,I have eaten generally the same foods but I do...,3,4,2,2.0,4,1.0,4.0,IT,Italian,1,3.0,"Pasta, chicken tender, pizza",1,4,4,4,6,"A lean protein such as grilled chicken, green ...",Ideally I would like to be able to eat healthi...,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and m...",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,3.0,3,NaN,A college student with an imbalanced diet tryi...,2,1.0,Eating Pizza as an excuse when there is nothin...,1,3,4,3.0,3,2.0,5.0,Doctor,Mexican Food,2,1.0,"Isombe , Plantains and Ugali",1,4,4,1,5,"A healthy meal is a variety of food , organic ...",Eating home cooked meals everyday and being ab...,5,2.0,5,5,7.0,1.0,Fried Rice \rBaked potatoes \rCurry Chicken,2.0,Public Health Advisor,3,1.0,3,4,1.0,4.0,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,3,NaN,"Rice, oatmeal, and tea",2,1.0,less rice,1,3,3,3.0,5,2.0,5.0,CEO of company,Korean,4,1.0,Rice and potato,1,4,3,5,6,lots of vegetables,lots of veggies,2,2.0,5,3,10.0,1.0,"meat, rice, kimchi",1.0,Real Estate manageer,3,1.0,2,4,5.0,4.0,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,3.0,7,1.0,I try to eat as healthy as possible everyday. ...,1,2.0,I don't eat as much on a daily basis since com...,1,8,5,2.0,2,1.0,3.0,Store manager at Giant Eagle,Italian,1,3.0,pizza and spaghetti,1,5,1,1,1,"A protein, a fruit, a starch, and a salad or s...",My ideal diet is the diet i am currently on. ...,6,4.0,1,5,1.0,1.0,"Pizza, Spaghetti, Baked Ziti",2.0,Receptionist for a medical supply company,4,1.0,2,3,1.0,2.0,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,3.0,high in protein and low in carbohydrates.,1,1.0,I have learned to eat more vegetables.,2,5,1,2.0,3,2.0,4.0,Journalist,HISPANIC CUISINE.,2,1.0,"rice, beans, and chicken / pizza/ tenders",1,3,3,2,3,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...",3,5.0,2,3,5.0,2.0,"Vegetables, Meat, and rice.",3.0,House-wife,5,1.0,3,3,2.0,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575,135
125,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,3.0,high in protein and low in carbohydrates.,1,1.0,I have learned to eat more vegetables.,2,5,1,2.0,3,2.0,4.0,Journalist,HISPANIC CUISINE.,2,1.0,"rice, beans, and chicken / pizza/ tenders",1,3,3,2,3,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...",3,5.0,2,3,5.0,2.0,"Vegetables, Meat, and rice.",3.0,House-wife,5,1.0,3,3,2.0,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [72]:
# Note that this does not show us all columns
pd.pandas.set_option('display.max_columns', None)

In [74]:
# See basic info - columns, non-null count, and datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           124 non-null    object
 1   Gender                        126 non-null    int64
 2   breakfast                     126 non-null    int64
 3   calories_chicken              126 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                125 non-null    float64
 6   coffee                        126 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  126 non-null    int64
 12  cuisine                       109 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            126 non-null    int64
 15  drink                         124 non-null    float64
 16  eating_changes                123 non-null    object
 17  eating_changes_coded          126 non-null    int64
 18  eating_changes_coded1         126 non-null    int64
 19  eating_out                    126 non-null    int64
 20  employment                    117 non-null    float64
 21  ethnic_food                   126 non-null    int64
 22  exercise                      113 non-null    float64
 23  father_education              125 non-null    float64
 24  father_profession             123 non-null    object
 25  fav_cuisine                   124 non-null    object
 26  fav_cuisine_coded             126 non-null    int64
 27  fav_food                      124 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         126 non-null    int64
 30  fruit_day                     126 non-null    int64
 31  grade_level                   126 non-null    int64
 32  greek_food                    126 non-null    int64
 33  healthy_feeling               126 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              126 non-null    int64
 37  income                        125 non-null    float64
 38  indian_food                   126 non-null    int64
 39  italian_food                  126 non-null    int64
 40  life_rewarding                125 non-null    float64
 41  marital_status                125 non-null    float64
 42  meals_dinner_friend           123 non-null    object
 43  mother_education              123 non-null    float64
 44  mother_profession             124 non-null    object
 45  nutritional_check             126 non-null    int64
 46  on_off_campus                 125 non-null    float64
 47  parents_cook                  126 non-null    int64
 48  pay_meal_out                  126 non-null    int64
 49  persian_food                  125 non-null    float64
 50  self_perception_weight        125 non-null    float64
 51  soup                          125 non-null    float64
 52  sports                        124 non-null    float64
 53  thai_food                     126 non-null    int64
 54  tortilla_calories             125 non-null    float64
 55  turkey_calories               126 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   126 non-null    int64
 58  vitamins                      126 non-null    int64
 59  waffle_calories               126 non-null    int64
 60  weight                        124 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 60.2+ KB

In [15]:
# See/describe basic statistics
df.describe()

,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current_coded,drink,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,fav_cuisine_coded,fav_food,fries,fruit_day,grade_level,greek_food,healthy_feeling,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,mother_education,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,veggies_day,vitamins,waffle_calories
count,126.000000,126.000000,126.000000,106.000000,125.000000,126.000000,106.000000,122.000000,126.000000,109.000000,126.000000,124.000000,126.000000,126.000000,126.000000,117.000000,126.000000,113.000000,125.000000,126.000000,124.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,125.000000,126.000000,126.000000,125.000000,125.000000,123.000000,126.000000,125.000000,126.000000,126.000000,125.000000,125.000000,125.00000,124.000000,126.000000,125.000000,126.000000,126.000000,126.000000,126.000000
mean,1.388889,1.111111,576.150794,3.028302,503.720000,1.753968,2.698113,2.786885,2.706349,1.403670,1.753968,1.556452,1.539683,4.555556,2.547619,2.444444,3.738095,1.592920,3.488000,2.420635,1.709677,1.087302,4.214286,2.380952,3.476190,5.436508,3.698413,4.536000,3.142857,4.714286,5.104000,1.504000,3.422764,3.166667,1.320000,1.539683,3.404762,2.800000,3.120000,1.21600,1.395161,3.325397,945.800000,553.373016,4.007937,1.515873,1069.444444
std,0.489444,0.315524,131.345594,0.639308,230.536632,0.432417,1.972042,1.038351,1.914440,0.982431,0.766149,0.498818,0.755257,2.537891,1.142679,0.532471,1.174247,0.663287,1.202256,1.940528,0.908623,0.283403,0.926129,1.130360,1.366539,2.584557,2.079499,1.451051,1.484395,0.604743,3.107805,0.548076,1.166529,1.211610,0.679184,0.755257,1.036753,1.419905,1.111523,0.41317,0.490869,1.435712,202.255827,152.908900,1.077003,0.501743,251.618936
min,1.000000,1.000000,265.000000,2.000000,315.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.00000,1.000000,1.000000,580.000000,345.000000,1.000000,1.000000,575.000000
25%,1.000000,1.000000,430.000000,3.000000,420.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,2.000000,3.000000,1.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,3.000000,3.000000,2.000000,4.000000,2.000000,5.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000,3.000000,2.000000,2.000000,1.00000,1.000000,2.000000,725.000000,500.000000,3.000000,1.000000,900.000000
50%,1.000000,1.000000,610.000000,3.000000,420.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,1.000000,4.000000,2.000000,2.000000,4.000000,1.000000,4.000000,1.000000,1.000000,1.000000,4.500000,2.000000,4.000000,5.000000,3.000000,5.000000,3.000000,5.000000,5.000000,1.000000,4.000000,3.000000,1.000000,1.000000,3.000000,3.000000,3.000000,1.00000,1.000000,3.000000,940.000000,500.000000,4.000000,2.000000,900.000000
75%,2.000000,1.000000,692.500000,3.000000,420.000000,2.000000,3.000000,3.000000,3.000000,1.000000,2.000000,2.000000,2.000000,5.000000,3.000000,3.000000,5.000000,2.000000,4.000000,4.000000,3.000000,1.000000,5.000000,3.000000,5.000000,8.000000,5.750000,6.000000,5.000000,5.000000,8.000000,2.000000,4.000000,4.000000,1.000000,2.000000,4.000000,4.000000,4.000000,1.00000,2.000000,5.000000,1165.000000,690.000000,5.000000,2.000000,1315.000000
max,2.000000,2.000000,720.000000,4.000000,980.000000,2.000000,9.000000,5.000000,9.000000,6.000000,4.000000,2.000000,4.000000,13.000000,5.000000,3.000000,5.000000,3.000000,5.000000,8.000000,3.000000,2.000000,5.000000,4.000000,5.000000,10.000000,8.000000,6.000000,5.000000,5.000000,10.000000,4.000000,5.000000,5.000000,4.000000,5.000000,6.000000,5.000000,6.000000,2.00000,2.000000,5.000000,1165.000000,850.000000,5.000000,2.000000,1315.000000

### 2. Structuring

Next we'll structure the data. We want to standardize the format and fix any formatting issues.  Are the units okay? Do we have any date/time issues? Are there case issues? ...

Helpful functions here:
* value_counts() for features that are categorical, we can see the unique categories and their counts https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html
* astype() for converting column to correct data type https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html
* fillna() for replacing NaNs with a number https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
* string manipulation functions (e.g. replace(), strip(), lower(), ...) https://www.w3schools.com/python/python_ref_string.asp
* and more

Example 1: One item to fix is employment. It should be 1, 2, 3, or 4 and we have instead floating-point numbers.  
Consider what type of data this really is? Categorical? Numerical? Nominal? Ordinal?

Why convert to a category if categorical? 
1. It saves memory space.
2. You can define a custom sort order for categorical data (e.g. XS, M, L, XL).
3. Faster calculation speed.

See [https://pandas.pydata.org/docs/user_guide/categorical.html](https://pandas.pydata.org/docs/user_guide/categorical.html) for more info on categories.

In [78]:
# Let's see what we have and then fix the data type (count the values)
print(df["employment"].value_counts())

#df["employment"] = df["employment"].astype(int) - cannot convert nulls
# we have nulls - let's use 0 to represent no answer -- need to fill these values before moving on
df["employment"] = df["employment"].fillna(0)
df["employment"] = df["employment"].astype("int")

# convert this to "category" type
df["employment"] = df["employment"].astype("category")
# look at describe at the top and now it will show employment as a series

# Let's see what we have and then fix the data type (count the values)
print(df["employment"].value_counts())

employment
2    61
3    54
0     9
1     2
Name: count, dtype: int64
employment
2    61
3    54
0     9
1     2
Name: count, dtype: int64

In [80]:
# check it out now - see info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           124 non-null    object
 1   Gender                        126 non-null    int64
 2   breakfast                     126 non-null    int64
 3   calories_chicken              126 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                125 non-null    float64
 6   coffee                        126 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  126 non-null    int64
 12  cuisine                       109 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            126 non-null    int64
 15  drink                         124 non-null    float64
 16  eating_changes                123 non-null    object
 17  eating_changes_coded          126 non-null    int64
 18  eating_changes_coded1         126 non-null    int64
 19  eating_out                    126 non-null    int64
 20  employment                    126 non-null    category
 21  ethnic_food                   126 non-null    int64
 22  exercise                      113 non-null    float64
 23  father_education              125 non-null    float64
 24  father_profession             123 non-null    object
 25  fav_cuisine                   124 non-null    object
 26  fav_cuisine_coded             126 non-null    int64
 27  fav_food                      124 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         126 non-null    int64
 30  fruit_day                     126 non-null    int64
 31  grade_level                   126 non-null    int64
 32  greek_food                    126 non-null    int64
 33  healthy_feeling               126 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              126 non-null    int64
 37  income                        125 non-null    float64
 38  indian_food                   126 non-null    int64
 39  italian_food                  126 non-null    int64
 40  life_rewarding                125 non-null    float64
 41  marital_status                125 non-null    float64
 42  meals_dinner_friend           123 non-null    object
 43  mother_education              123 non-null    float64
 44  mother_profession             124 non-null    object
 45  nutritional_check             126 non-null    int64
 46  on_off_campus                 125 non-null    float64
 47  parents_cook                  126 non-null    int64
 48  pay_meal_out                  126 non-null    int64
 49  persian_food                  125 non-null    float64
 50  self_perception_weight        125 non-null    float64
 51  soup                          125 non-null    float64
 52  sports                        124 non-null    float64
 53  thai_food                     126 non-null    int64
 54  tortilla_calories             125 non-null    float64
 55  turkey_calories               126 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   126 non-null    int64
 58  vitamins                      126 non-null    int64
 59  waffle_calories               126 non-null    int64
 60  weight                        124 non-null    object
dtypes: category(1), float64(19), int64(27), object(14)
memory usage: 59.5+ KB

Example 2: Favorite cuisine looks messy. Let's ensure all the field values are in lowercase.

In [82]:
# See the problem first (count the values)
df["fav_cuisine"].value_counts()
# Fix the string case
df["fav_cuisine"] = df["fav_cuisine"].str.lower()
# remove word "food" (replace) - we already forced this to lowercase
df["fav_cuisine"] = df["fav_cuisine"].str.replace("food|cuisine|\\.", "", regex=True)
# remove/strip extra spaces
df["fav_cuisine"] = df["fav_cuisine"].str.strip()
# See fixed
df["fav_cuisine"].value_counts()

fav_cuisine
italian                                 51
mexican                                 12
chinese                                  7
american                                 7
thai                                     3
asian                                    3
indian                                   3
american or italian                      2
hispanic                                 2
korean                                   2
sushi                                    1
nepali                                   1
lebanese or greek                        1
wraps                                    1
i really love italian  and thai          1
barbecue                                 1
italian and chinese                      1
authentic chinese and vietnamese         1
mac and cheese                           1
any type of colombian                    1
japanese                                 1
i do not like                            1
vietnamese                               1
lean                                     1
chinese  (general tso's)                 1
arabic                                   1
sub sandwhiches                          1
all                                      1
italian or chinese                       1
french                                   1
spanish                                  1
indian  - samosas are amazing            1
italian/german                           1
don't have one                           1
chicken                                  1
jamaican                                 1
orange chicken and chow mani noodles     1
sea                                      1
anything american style                  1
african                                  1
turkish                                  1
greek                                    1
Name: count, dtype: int64

There is much, much more we can do to structure the data, and we'll do a little more of this next week. But let's look at the next step for now.

### 3. Data Cleaning

We look for dirty data (e.g. duplicates, missing data, outliers, duplicates).  There are many functions what will help us here, such as:
* duplicated() to determine which records/observations/instances are duplicates
* drop_duplicates() to drop duplicate records
* isnull() to detect missing values - returns boolean values
* dropna() to drop rows with missing values
* drop() to drop a feature/column

Let's begin by finding any rows that are duplicates of other rows. If we find any duplicated rows, let's remove them.

In [84]:
# check for duplicates
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
121    False
122    False
123    False
124    False
125     True
Length: 126, dtype: bool

In [86]:
# Let's see which records are duplicates
df[df.duplicated()]

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
125,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,3.0,high in protein and low in carbohydrates.,1,1.0,I have learned to eat more vegetables.,2,5,1,2,3,2.0,4.0,Journalist,hispanic,2,1.0,"rice, beans, and chicken / pizza/ tenders",1,3,3,2,3,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...",3,5.0,2,3,5.0,2.0,"Vegetables, Meat, and rice.",3.0,House-wife,5,1.0,3,3,2.0,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [88]:
# Let's drop the duplicate
df = df.drop_duplicates()

Next we'll consider if data is missing. Let's review what is missing first and then decide next steps.

In [90]:
# Let's see what fields are missing data
missing = df.isnull().sum().sort_values()
print(missing)
print(type(missing))

fruit_day                      0
italian_food                   0
indian_food                    0
ideal_diet_coded               0
healthy_feeling                0
                              ..
exercise                      13
cuisine                       17
comfort_food_reasons_coded    19
calories_day                  19
type_sports                   26
Length: 61, dtype: int64
<class 'pandas.core.series.Series'>

In [43]:
# cheating - convert series to a string to print it all
df.isnull().sum().sort_values().to_string()

'fruit_day                        0\nitalian_food                     0\nindian_food                      0\nideal_diet_coded                 0\nhealthy_feeling                  0\ngreek_food                       0\ngrade_level                      0\nwaffle_calories                  0\nfries                            0\nparents_cook                     0\nfav_cuisine_coded                0\npay_meal_out                     0\nemployment                       0\neating_out                       0\neating_changes_coded1            0\neating_changes_coded             0\nethnic_food                      0\nnutritional_check                0\ndiet_current_coded               0\nthai_food                        0\nGender                           0\nbreakfast                        0\ncomfort_food_reasons_coded.1     0\ncalories_chicken                 0\nturkey_calories                  0\nveggies_day                      0\ncoffee                           0\nvitamins                         0\nmarital_status                   1\nlife_rewarding                   1\nincome                           1\nideal_diet                       1\nhealthy_meal                     1\ncomfort_food                     1\nsoup                             1\nfood_childhood                   1\ntortilla_calories                1\npersian_food                     1\nfather_education                 1\nself_perception_weight           1\non_off_campus                    1\ndiet_current                     1\ncalories_scone                   1\nsports                           2\nGPA                              2\nfav_food                         2\nfav_cuisine                      2\ndrink                            2\ncomfort_food_reasons             2\nmother_profession                2\nweight                           2\nmother_education                 3\nmeals_dinner_friend              3\nfather_profession                3\neating_changes                   3\ncook                             3\nexercise                        13\ncuisine                         17\ncomfort_food_reasons_coded      19\ncalories_day                    19\ntype_sports                     26'

In [92]:
missing[missing > 5]

exercise                      13
cuisine                       17
comfort_food_reasons_coded    19
calories_day                  19
type_sports                   26
dtype: int64

If all the values are missing, we really should drop the row/observation.

In [55]:
# drop rows where all (how) data is na
df = df.dropna(how="all")

If a row is missing a significant number of values, we can then drop that row.

In [58]:
# Let's drop rows missing more than 5 values (threshold)
df = df.dropna(thresh=len(df.columns)-5)

We need to consider what percentage of values are missing from a feature and if it is random or not. Depending on how much data is missing, we'll take different actions.

Let's check out calories_day. Which rows are missing values? Is there a certain population that does not provide this data? Is the data missing at random, or is there a pattern? What percentage of the values are missing?

In [94]:
# which fields are missing calories - let's explore this data (filter by is null)
df[df["calories_day"].isnull()]

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,2.0,9,NaN,eat good and exercise,1,1.0,eat faster,1,1,3,3,1,1.0,5.0,profesor,arabic,3,1.0,rice and chicken,2,5,2,5,2,looks not oily,being healthy,8,5.0,5,5,1.0,1.0,"rice, chicken, soup",1.0,unemployed,5,1.0,1,2,5.0,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
8,3.3,1,1,430,NaN,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,3.0,2,1.0,I eat whatever I want in moderation.,1,1.0,I snack less,2,8,5,2,5,NaN,5.0,High School Principal,sea,1,3.0,"Shrimp, spaghetti",1,4,1,5,7,Colorful,The same as it is now.,6,5.0,5,5,8.0,2.0,"Pasta, Fish, Steak",5.0,Elementary School Teacher,2,1.0,2,3,5.0,4.0,2.0,2.0,5,725.0,345,none,3,2,760,180
15,NaN,2,2,430,NaN,980.0,2,"cookies, donuts, candy bars",boredom,2.0,4.0,2,1.0,I like a lot of foods that arent home cooked o...,2,2.0,none,3,4,4,3,1,1.0,5.0,Hockey Coach,italian,1,2.0,pizza,1,3,1,1,6,"chicken, veggies, rice",I wish I ate lots of healthy foods like veggie...,2,4.0,1,5,NaN,2.0,pizza buffalo chicken pasta,4.0,Librarian,1,1.0,2,3,1.0,2.0,2.0,1.0,1,940.0,345,Hockey,1,2,1315,180
39,3,2,1,720,NaN,980.0,2,Candy\rPop\rChocolate \rChipotle \rMoe's,No reasons,9.0,5.0,9,1.0,Unhealthy foods from the cafe,2,2.0,I eat more,1,2,5,3,3,1.0,5.0,Corporate Manager,mexican,2,1.0,Chicken and steak,1,5,4,1,3,Chicken breast with veggies,"Red and white meats, potatoes, green beans",2,6.0,3,4,5.0,2.0,"Steak and potatoes, burgers and fries, bacon a...",2.0,Marketing Analyst,1,2.0,3,3,1.0,1.0,1.0,1.0,3,1165.0,690,Hockey,3,2,1315,175
47,2.8,2,1,430,NaN,980.0,2,"Chex-mix, Wegmans cookies, Cheez-Its","Boredom, happiness, distraught",2.0,4.0,2,1.0,lots of pasta and carbs along with lean meats....,2,1.0,Cereal became an anytime of day food,1,3,2,0,3,1.0,5.0,small business owner,italian,1,3.0,"lasagna, meatloaf, pizza",1,5,1,3,8,"good balance between meats, grains, fruits, ve...",To cut out the junk food and eat more meat and...,7,6.0,2,4,9.0,1.0,"lasagna, hamburgers w/ corn, steak",5.0,nurse,2,1.0,1,3,4.0,2.0,1.0,1.0,1,940.0,345,wrestling & rowing,5,2,900,145
48,3.5,2,2,430,NaN,315.0,1,"pizza, ice cream, chips","stressed, upset, or just craving a cheat meal",1.0,4.0,1,1.0,"My current diet consists of cafeteria food, wh...",2,2.0,Transitioning from home-cooked meals to cafete...,1,3,2,3,4,1.0,4.0,House Appraiser,asian,4,1.0,"Tacos, Spaghetti, and Roast",1,5,2,4,2,one that is well balanced and consists on main...,One that consists of a lot of mean and also fr...,7,5.0,4,5,3.0,1.0,"Steak, Chicken, Tacos",4.0,Banker,3,1.0,1,3,4.0,1.0,2.0,1.0,4,940.0,345,Wrestling,5,1,760,155
53,3.292,2,1,610,NaN,980.0,2,"fries, chips, fried chicken, pizza, grapes","Boredom, sadness",2.0,4.0,2,1.0,65 and out,4,2.0,NaN,3,4,3,0,3,NaN,2.0,HVAC Professional,sub sandwhiches,5,3.0,"Chicken, Pizza, Cherry tomatoes",1,4,4,4,5,"Grilled, natural ingredients, and no carbonate...",Blend of instant gratification and healthy cho...,3,3.0,2,5,1.0,1.0,"Pizza, Steak, Spaghetti",5.0,"Counseling, Teaching, Geologist, Psychic",1,3.0,1,3,3.0,4.0,1.0,2.0,1,940.0,500,NaN,4,1,1315,265
59,3.7,1,1,610,NaN,420.0,2,Mac n Cheese. Chips and salsa. Ice cream.,Boredom. Celebration.,2.0,2.0,2,1.0,Simple breakfast of cereal or yogurt. Lunch is...,3,2.0,More snacking,1,11,2,3,5,NaN,4.0,Insurance,italian,1,3.0,Mac and cheese,1,5,4,5,7,Proper serving sizes of almost anything,Less cheese than I eat.,1,6.0,5,5,10.0,1.0,Steak and veggies. Chicken and rice. Stirfry.,4.0,Real Estate Agent,2,2.0,2,3,4.0,3.0,2.0,1.0,5,1165.0,500,skiing,4,2,1315,155
65,3.2,1,1,610,NaN,315.0,2,mac and cheese,boredom,2.0,2.0,2,2.0,"I don't follow a diet, I eat whatever I want",2,1.0,"I snack more, having fewer full meals",1,11,3,3,3,2.0,5.0,Dentist,italian,1,3.0,"Mac and Cheese, Chicken nuggets",1,3,2,3,3,vegtables,"No, diet",6,6.0,1,5,3.0,2.0,"Lasagna, Steak, Pasta",NaN,Periodontist,1,1.0,2,5,1.0,2.0,1.0,2.0,4,725.0,500,NaN,3,2,900,112
71,4,1,1,720,NaN,420.0,2,"Chocolate, ice cream, cookie dough","Boredom, being in your period, and long bus ri...",2.0,2.0,2,1.0,"My meals consist of a vegetable, a meat and us...",1,1.0,I tend to snack more and have smaller meals.,1,11,1,2,5,1.0,2.0,Transportation,italian,1,1.0,Spaghetti,2,5,3,3,5,"A balanced meal with a protein, carbohydrate a...","I would like to eat less carbohydrates, such a...",3,5.0,4,5,2.0,2.0,"Spaghetti, steak, or chicken",4.0,Social Services,4,1.0,1,6,3.0,4.0,1.0,1.0,4,1165.0,690,Softball,5,1,1315,140
82,3.7,1,1,265,NaN,315.0,2,"pizza, ice cream, cookies",boredom,2.0,NaN,2,1.0,I eat two-tree meals per day. Always eat a bre...,4,2.0,Food is not as healthy.,1,3,5,3,4,1.0,4.0,Works for Kirila Fire,italian,1,1.0,spaghetti and tacos,1,3,3,3,8,lots of colors,A good breakfast. A healthy lunch and dinner.,2,3.0,3,5,7.0,1.0,"pizza, tacos, pasta",4.0,works in Loans department in First National Bank,3,1.0,2,3,3.0,3.0,1.0,1.0,3,580.0,345,wrestling,3,2,575,170
92,3.3,2,2,720,NaN,420.0,2,"Chocolate, Chips, Ice cream, French Fires, Pizza","Stress, sadness, boredom",1.0,2.0,1,1.0,My diet consists of high levels of meats with ...,2,2.0,I have increased the amounts of vegetables I e...,2,5,5,2,1,3.0,2.0,Truck Driver,barbecue,5,1.0,"Steak, Chicken Tenders, Pizza",1,1,3,1,8,Chicken Salad with Pita Chips,A balance between meats and vegetables with le...,3,3.0,1,5,1.0,2.0,"Chicken, Pork Chops, Steak",3.0,Customer Service Representative,2,1.0,1,3,1.0,4.0,1.0,1.0,1,1165.0,690,"Football, Basketball, Volleyball, Golf",4,2,900,190
93,3.2,2,1,720,NaN,420.0,2,"Mac and cheese, lasagna, Chinese food","Boredom, sadness",2.0,4.0,2,1.0,Very poor. Heavy carb consumption.,2,2.0,I eat alot of carbs and eat much more frequently,1,2,2,3,5,3.0,5.0,Senior Manager,italian,1,1.0,"Spaghetti, Italian potato soup",1,4,1,4,6,"Fruits, vegetables, meat",Alot of fruits and veggies. Meat and bread. Wa...,2,4.0,5,5,6.0,1.0,"Salmon, hamburger surprise, Italian potato soup",4.0,Stay at home mother,1,1.0,1,4,5.0,3.0,1.0,2.0,5,1165.0,690,NaN,5,2,1315,165
95,3.5,2,1,265,NaN,420.0,2,"Doritos, mac and cheese, ice cream","Boredom, hunger, snacking.",2.0,3.0,2,1.0,"I eat usually 2 times a day, either breakfast ...",2,2.0,Food is readily available so I don't have to c...,1,2,2,3,4,1.0,4.0,Supervisor,american,5,3.0,Macaroni and Cheese,1,4,3,4,10,a balance of Meat and vegetables,I like the diet I have now. I could eat 3 tim...,6,5.0,3,5,10.0,2.0,"Pasta, fish, steak",4.0,Treasurer,3,1.0,1,3,3.0,2.0,2.0,1.0,4,1165.0,690,Wrestling,4,2,1315,184
101,3.4,1,1,610,NaN,420.0,2,"macaroni and cheese, stuffed peppers, hamburge...","boredom, stress, mood swings",2.0,3.0,2,1.0,At this time it is very touch and go. Some day...,2,2.0,I eat a lot more carbs than I did when I lived...,1,11,2,2,5,3.0,4.0,salesman,sushi,4,3.0,"chicken nuggets, macaroni and cheese",1,5,1,5,3,More vegetables and fruits as opposed to meat ...,"If at all possible, I would like to be able to...",2,5.0,4,5,3.0,1.0,NaN,4.0,social worker,4,1.0,1,2,4.0,5.0,1.0,2.0,3,1165.0,500,NaN,5,2,1315,160
116,3.4,1,1,610,NaN,420.0,2,"Ice cream, chocolate, pizza, cucumber","loneliness, homework, boredom",NaN,3.0,2,NaN,"It is very unbalance. Mostly fat food, Lack of...",2,1.0,less vegetable more sweats,1,3,4,3,4,2.0,3.0,Business Man,chinese,4,2.0,"Fry Chicken, Rice Vegetable",1,5,1,1,5,BBQ Chicken with mash sweat potatoes and steam...,Very healthy. Freshly done. properly cooked,5,1.0,3,5,2.0,1.0,"Rice and Peas and Chicken, Jerk Chicken and Sh...",3.0,Business Woman,2,1.0,2,3,1.0,4.0,1.0,2.0,5,725.0,345,none,5,1,1315,170
117,3.77,1,1,610,NaN,315.0,2,"Noodle ( any kinds of noodle), Tuna sandwich, ...",When i'm eating with my close friends/ Food s...,NaN,3.0,5,4.0,I eat in dining hall of school everyday. I usu...,1,1.0,"I eat more vegetable. Since coming to college,...",2,5,2,2,4,NaN,2.0,His own business,vietnamese,4,3.0,"Noodle, Wings, and Tiramisu",1,3,2,2,9,Including both vegetable and meat,My ideal diet should include both vegetable an...,2,2.0,2,4,7.0,1.0,"Vietnamese fried rolls, Pho, Some kinds of noo...",2.0,Her own business,2,1.0,1,2,2.0,4.0,1.0,2.0,5,725.0,690,"No, I don't play sport.",3,1,760,113
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,3.0,3,NaN,"Rice, oatmeal, and tea",2,1.0,less rice,1,3,3,3,5,2.0,5.0,CEO of company,korean,4,1.0,Rice and potato,1,4,3,5,6,lots of vegetables,lots of veggies,2,2.0,5,3,10.0,1.0,"meat, rice, kimchi",1.0,Real Estate manageer,3,1.0,2,4,5.0,4.0,1.0,2.0,5,580.0,690,none,4,2,1315,120
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,NaN,5,3.0,high in protein and low in carbohydrates.,1,1.0,I have learned to eat more vegetables.,2,5,1,2,3,2.0,4.0,Journalist,hispanic,2,1.0,"rice, beans, and chicken / pizza/ tenders",1,3,3,2,3,"a cup of rice, vegetables, and meat.","Being able to balance between sweets, vegetabl...",3,5.0,2,3,5.0,2.0,"Vegetables, Meat, and rice.",3.0,House-wife,5,1.0,3,3,2.0,3.0,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [96]:
# Let's look at calories_day - what percentage of records is missing?
df["calories_day"].isnull().sum()/len(df)

0.152

In [98]:
# for 15%, let's fill the missing values (na) with the mean or median
# check if we want mean or median
print(df["calories_day"].value_counts())

# get mean or median
new_value = df["calories_day"].value_counts().idxmax()
print("New value is", new_value)

# replace missing values with mean or median
df["calories_day"] = df["calories_day"].fillna(new_value)
print(df["calories_day"].value_counts())

calories_day
3.0    63
4.0    23
2.0    20
Name: count, dtype: int64
New value is 3.0
calories_day
3.0    82
4.0    23
2.0    20
Name: count, dtype: int64

C:\Users\alm36\AppData\Local\Temp\ipykernel_13264\334326354.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["calories_day"] = df["calories_day"].fillna(new_value)

If more than 50% of the values of a feature are missing, we'd most likely drop the feature.

In [ ]:
# if type_sports was a high percentage (let's say 60%) we should just remove/drop the feature

To be continued next class